label images_import:


    image epiclustbanneridle = "Icons/epicidle.png"
    image epiclustbannerhover = "Icons/epichover.png"

# sprites

    image side playersprite = "Sprites/PlayerSprite.png"
    image side nikkisprite = "Sprites/NikkiSprite.png"
    image side nancysprite = "Sprites/NancySprite.png"
    image side debbysprite = "Sprites/DebbySprite.png"
    image side katesprite = "Sprites/KateSprite.png"
    image side teagansprite = "Sprites/TeaganSprite.png"
    image side sophiasprite = "Sprites/SophiaSprite.png"
    image side annasprite = "Sprites/AnnaSprite.png"
    image side chantellesprite = "Sprites/ChantelleSprite.png"
    image side friedasprite = "Sprites/FriedaSprite.png"
    image side katsumisprite = "Sprites/KatsumiSprite.png"
    image side mariasprite = "Sprites/MariaSprite.png"
    image side dorissprite = "Sprites/DorisSprite.png"
    image side hallesprite = "Sprites/HalleSprite.png"
    image side daniellasprite = "Sprites/DaniellaSprite.png"
    image side pamelasprite = "Sprites/PamelaSprite.png"
    image side jennifersprite = "Sprites/JenniferSprite.png"
    image side laurasprite = "Sprites/LauraSprite.png"
    image side sandysprite = "Sprites/SandySprite.png"
    image side chiyosprite = "Sprites/ChiyoSprite.png"
    image side tanyasprite = "Sprites/TanyaSprite.png"
    image side vivianesprite = "Sprites/VivianeSprite.png"
    image side brittanysprite = "Sprites/BrittanySprite.png"
    image side francinesprite = "Sprites/FrancineSprite.png"
    image side maddysprite = "Sprites/MaddySprite.png"

    image side josesprite = "Sprites/JoseSprite.png"
    image side hostsprite = "Sprites/HostSprite.png"
    image side captainsprite = "Sprites/CaptainSprite.png"
    image side beachsprite = "Sprites/BeachSprite.png"
    image side shopsprite = "Sprites/ShopSprite.png"
    image side quentinsprite = "Sprites/QuentinSprite.png"
    image side oldwomansprite = "Sprites/OldWomanSprite.png"
    image side randychicksprite = "Sprites/RandyChickSprite.png"
    image side randyboysprite = "Sprites/RandyBoySprite.png" 
    image side williesprite = "Sprites/WillieSprite.png"
    image side allisonsprite = "Sprites/AllisonSprite.png"
    image side gothkidsprite = "Sprites/GothKidSprite.png"
    image side frenchchicksprite = "Sprites/FrenchChickSprite.png"
    image side copsprite = "Sprites/CopWomanSprite.png"
    image side lollysprite = "Sprites/LollySprite.png"
    image side securitysprite = "Sprites/SecuritySprite.png"
    image side gimpsprite = "Sprites/GimpSprite.png"
    image side kimsprite = "Sprites/KimSprite.png"
    image side lesbianonesprite = "Sprites/Lesbian01Sprite.png"
    image side lesbiantwosprite = "Sprites/Lesbian02Sprite.png"
    image side secretarysprite = "Sprites/SecretarySprite.png"
    image side mitchsprite = "Sprites/MitchSprite.png"
    image side darrylsprite = "Sprites/DarrylSprite.png"
    image side babasprite = "Sprites/BabaSprite.png"
    image side fatguysprite = "Sprites/FatGuySprite.png"
    image side angelinasprite = "Sprites/AngelinaSprite.png"
    image side nerdysprite = "Sprites/NerdySprite.png"
    image side musclechicksprite = "Sprites/MuscleChickSprite.png"
    image side redshopsprite = "Sprites/RedSprite.png"
    image side blondshopsprite = "Sprites/BlondeSprite.png"
    image side pasystemsprite = "Sprites/PASystemSprite.png"
    image side lyrebirdsprite = "Sprites/LyrebirdSprite.png"
    image side nobodysprite = "Sprites/NobodySprite.png"
    image side doctorsprite = "Sprites/DoctorSprite.png"
    image side racksprite = "Sprites/RacksSprite.png"
    image side shadyguysprite = "Sprites/ShadyGuySprite.png"
    image side oldjoesprite = "Sprites/OldJoeSprite.png"
    image side firemansprite = "Sprites/FiremanSprite.png"
    image side sweden01sprite = "Sprites/Sweden01Sprite.png"
    image side sweden02sprite = "Sprites/Sweden02Sprite.png"
    image side mexicansprite = "Sprites/MexicanSprite.png"
    image side hendersongirlsprite = "Sprites/HendersonGirlSprite.png"
    
    
# Character Sheets
    image charactersheets = "Sheets/charactersheets.jpg"
    image anna01 = "Sheets/anna02.jpg"
    image brittany02 = "Sheets/brittany02.jpg"
    image chantelle02 = "Sheets/chantelle02.jpg"
    image chiyo02 = "Sheets/chiyo02.jpg"
    image daniella02 = "Sheets/daniella02.jpg"
    image debby02 = "Sheets/debby02.jpg"
    image doris02 = "Sheets/doris02.jpg"
    image francine02 = "Sheets/francine02.jpg"
    image frieda02 = "Sheets/frieda02.jpg"
    image halle02 = "Sheets/halle02.jpg"
    image jennifer02 = "Sheets/jennifer02.jpg"
    image kate02 = "Sheets/kate02.jpg"
    image katsumi02 = "Sheets/katsumi02.jpg"
    image laura02 = "Sheets/laura02.jpg"
    image maddy02 = "Sheets/maddy02.jpg"
    image maria02 = "Sheets/maria02.jpg"
    image nancy02 = "Sheets/nancy02.jpg"
    image nikki02 = "Sheets/nikki02.jpg"
    image pamela02 = "Sheets/pamela02.jpg"
    image sandy02 = "Sheets/sandy02.jpg"
    image sophia02 = "Sheets/sophia02.jpg"
    image tanya02 = "Sheets/tanya02.jpg"
    image teagan02 = "Sheets/teagan02.jpg"
    image viviane02 = "Sheets/viviane02.jpg"
        
    image CGbackground = "Gallery/CGbackground.jpg"
    
    transform annablinking:
        "Sheets/annasheet01.png"
        pause 4.0
        "Sheets/annasheet01b.png"
        pause 0.1
        repeat
        
    transform annablinkingb:
        "Sheets/annasheet02.png"
        pause 4.0
        "Sheets/annasheet02b.png"
        pause 0.1
        repeat

    transform brittanyblinking:
        "Sheets/brittanysheet01.png"
        pause 4.0
        "Sheets/brittanysheet01b.png"
        pause 0.1
        repeat

    transform brittanyblinkingb:
        "Sheets/brittanysheet02.png"
        pause 4.0
        "Sheets/brittanysheet02b.png"
        pause 0.1
        repeat

    transform chantelleblinking:
        "Sheets/chantellesheet01.png"
        pause 4.0
        "Sheets/chantellesheet01b.png"
        pause 0.1
        repeat

    transform chantelleblinkingb:
        "Sheets/chantellesheet02.png"
        pause 4.0
        "Sheets/chantellesheet02b.png"
        pause 0.1
        repeat

    transform chiyoblinking:
        "Sheets/chiyosheet01.png"
        pause 4.0
        "Sheets/chiyosheet01b.png"
        pause 0.1
        repeat

    transform chiyoblinkingb:
        "Sheets/chiyosheet02.png"
        pause 4.0
        "Sheets/chiyosheet02b.png"
        pause 0.1
        repeat

    transform daniellablinking:
        "Sheets/daniellasheet01.png"
        pause 4.0
        "Sheets/daniellasheet01b.png"
        pause 0.1
        repeat

    transform daniellablinkingb:
        "Sheets/daniellasheet02.png"
        pause 4.0
        "Sheets/daniellasheet02b.png"
        pause 0.1
        repeat

    transform debbyblinking:
        "Sheets/debbysheet01.png"
        pause 4.0
        "Sheets/debbysheet01b.png"
        pause 0.1
        repeat

    transform debbyblinkingb:
        "Sheets/debbysheet02.png"
        pause 4.0
        "Sheets/debbysheet02b.png"
        pause 0.1
        repeat

    transform dorisblinking:
        "Sheets/dorissheet01.png"
        pause 4.0
        "Sheets/dorissheet01b.png"
        pause 0.1
        repeat

    transform dorisblinkingb:
        "Sheets/dorissheet02.png"
        pause 4.0
        "Sheets/dorissheet02b.png"
        pause 0.1
        repeat

    transform francineblinking:
        "Sheets/francinesheet01.png"
        pause 4.0
        "Sheets/francinesheet01b.png"
        pause 0.1
        repeat

    transform francineblinkingb:
        "Sheets/francinesheet02.png"
        pause 4.0
        "Sheets/francinesheet02b.png"
        pause 0.1
        repeat

    transform friedablinking:
        "Sheets/friedasheet01.png"
        pause 4.0
        "Sheets/friedasheet01b.png"
        pause 0.1
        repeat

    transform friedablinkingb:
        "Sheets/friedasheet02.png"
        pause 4.0
        "Sheets/friedasheet02b.png"
        pause 0.1
        repeat

    transform halleblinking:
        "Sheets/hallesheet01.png"
        pause 4.0
        "Sheets/hallesheet01b.png"
        pause 0.2
        repeat

    transform halleblinkingb:
        "Sheets/hallesheet02.png"
        pause 4.0
        "Sheets/hallesheet02b.png"
        pause 0.1
        repeat

    transform jenniferblinking:
        "Sheets/jennifersheet01.png"
        pause 4.0
        "Sheets/jennifersheet01b.png"
        pause 0.2
        repeat

    transform jenniferblinkingb:
        "Sheets/jennifersheet02.png"
        pause 4.0
        "Sheets/jennifersheet02b.png"
        pause 0.2
        repeat

    transform kateblinking:
        "Sheets/katesheet01.png"
        pause 4.0
        "Sheets/katesheet01b.png"
        pause 0.1
        repeat

    transform kateblinkingb:
        "Sheets/katesheet02.png"
        pause 4.0
        "Sheets/katesheet02b.png"
        pause 0.1
        repeat

    transform katsumiblinking:
        "Sheets/katsumisheet01.png"
        pause 4.0
        "Sheets/katsumisheet01b.png"
        pause 0.1
        repeat

    transform katsumiblinkingb:
        "Sheets/katsumisheet02.png"
        pause 4.0
        "Sheets/katsumisheet02b.png"
        pause 0.2
        repeat

    transform laurablinking:
        "Sheets/laurasheet01.png"
        pause 4.0
        "Sheets/laurasheet01b.png"
        pause 0.2
        repeat

    transform laurablinkingb:
        "Sheets/laurasheet02.png"
        pause 4.0
        "Sheets/laurasheet02b.png"
        pause 0.1
        repeat

    transform maddyblinking:
        "Sheets/maddysheet01.png"
        pause 4.0
        "Sheets/maddysheet01b.png"
        pause 0.1
        repeat

    transform maddyblinkingb:
        "Sheets/maddysheet02.png"
        pause 4.0
        "Sheets/maddysheet02b.png"
        pause 0.1
        repeat

    transform mariablinking:
        "Sheets/mariasheet01.png"
        pause 4.0
        "Sheets/mariasheet01b.png"
        pause 0.1
        repeat

    transform mariablinkingb:
        "Sheets/mariasheet02.png"
        pause 4.0
        "Sheets/mariasheet02b.png"
        pause 0.1
        repeat

    transform nancyblinking:
        "Sheets/nancysheet01.png"
        pause 4.0
        "Sheets/nancysheet01b.png"
        pause 0.1
        repeat

    transform nancyblinkingb:
        "Sheets/nancysheet02.png"
        pause 4.0
        "Sheets/nancysheet02b.png"
        pause 0.1
        repeat

    transform nikkiblinking:
        "Sheets/nikkisheet01.png"
        pause 4.0
        "Sheets/nikkisheet01b.png"
        pause 0.1
        repeat

    transform nikkiblinkingb:
        "Sheets/nikkisheet02.png"
        pause 4.0
        "Sheets/nikkisheet02b.png"
        pause 0.1
        repeat

    transform pamelablinking:
        "Sheets/pamelasheet01.png"
        pause 4.0
        "Sheets/pamelasheet01b.png"
        pause 0.1
        repeat

    transform pamelablinkingb:
        "Sheets/pamelasheet02.png"
        pause 4.0
        "Sheets/pamelasheet02b.png"
        pause 0.1
        repeat

    transform sandyblinking:
        "Sheets/sandysheet01.png"
        pause 4.0
        "Sheets/sandysheet01b.png"
        pause 0.1
        repeat

    transform sandyblinkingb:
        "Sheets/sandysheet02.png"
        pause 4.0
        "Sheets/sandysheet02b.png"
        pause 0.1
        repeat

    transform sophiablinking:
        "Sheets/sophiasheet01.png"
        pause 4.0
        "Sheets/sophiasheet01b.png"
        pause 0.1
        repeat

    transform sophiablinkingb:
        "Sheets/sophiasheet02.png"
        pause 4.0
        "Sheets/sophiasheet02b.png"
        pause 0.1
        repeat

    transform tanyablinking:
        "Sheets/tanyasheet01.png"
        pause 4.0
        "Sheets/tanyasheet01b.png"
        pause 0.1
        repeat

    transform tanyablinkingb:
        "Sheets/tanyasheet02.png"
        pause 4.0
        "Sheets/tanyasheet02b.png"
        pause 0.1
        repeat

    transform teaganblinking:
        "Sheets/teagansheet01.png"
        pause 4.0
        "Sheets/teagansheet01b.png"
        pause 0.1
        repeat

    transform teaganblinkingb:
        "Sheets/teagansheet02.png"
        pause 4.0
        "Sheets/teagansheet02b.png"
        pause 0.1
        repeat

    transform vivianeblinking:
        "Sheets/vivianesheet01.png"
        pause 4.0
        "Sheets/vivianesheet01b.png"
        pause 0.1
        repeat

    transform vivianeblinkingb:
        "Sheets/vivianesheet02.png"
        pause 4.0
        "Sheets/vivianesheet02b.png"
        pause 0.1
        repeat

# # Day1 images

    image black = "Day1/blackscreen.jpg"
    image beachbar01 = "Day1/beachbar01.jpg"
    image beachbar02 = "Day1/beachbar02.jpg"
    image beachbar03 = "Day1/beachbar03.jpg"
    image bathroomday = "Day1/bathroomday.jpg"
    image bathroomnight = "Day1/bathroomnight.jpg"
    image housepoolempty = "Day1/housepoolempty.jpg"
    image ryanmirror = "Day1/ryanmirror.jpg"
    image ryanbedroomday = "Day1/ryanbedroomday.jpg"
    image ryanbedroomnight = "Day1/ryanbedroomnight.jpg"
    image ryanworkout01 = "Day1/ryanworkout01.jpg"
    image ryansleeping = "Day1/ryansleeping.jpg"
    image nancybedroom01 = "Day1/nancybedroom01.jpg"
    image livingroom01 = "Day1/livingroom01.jpg"
    image sisroom01 = "Day1/sisbedroom01.jpg"
    image sisbedroomnight = "Day1/sisbedroomnight.jpg"
    image nancysleeping01 = "Day1/nancysleeping01.jpg"
    image nancybedroomday = "Day1/nancybedroomday.jpg"
    image nancysleeping02 = "Day1/nancysleeping02.jpg"
    image nancysleeping03 = "Day1/nancysleeping03.jpg"
    image nancysleeping04 = "Day1/nancysleeping04.jpg"
    image cardrive = "Day1/cardrive.jpg"
    image busdrive = "Day1/busdrive.jpg"
    image randybeach01 = "Day1/randybeach01.jpg"
    image randybeacholdbackground = "Day1/randybeacholdbackground.jpg"
    image randybeachcouple01 = "Day1/randybeachcouple01.jpg"
    image randybeachcouplefuck = "Day1/randybeachcouplefuck.jpg"
    image randybeachcouplecum = "Day1/randybeachcouplecum.jpg"
    image randybeachcouplethreesome = "Day1/randybeachcouplethreesome.jpg"
    image randybeachcouplethreesomecum = "Day1/randybeachcouplethreesomecum.jpg"
    image randybeachsandy01 = "Day1/randybeachsandy01.jpg"
    image randybeachsandy02 = "Day1/randybeachsandy02.jpg"
    image randybeachsandy03 = "Day1/randybeachsandy03.jpg"
    image randybeachsandy04 = "Day1/randybeachsandy04.jpg"
    image randybeachsandy05 = "Day1/randybeachsandy05.jpg"
    image randybeachsandy06 = "Day1/randybeachsandy06.jpg"
    image randybeachsandycum = "Day1/randybeachsandycum.jpg"
    image randybeachsandykiss = "Day1/randybeachsandykiss.jpg"
    image randybeachsandykisscum = "Day1/randybeachsandykisscum.jpg"
    image randybeachsandywank01 = "Day1/randybeachsandywank01.jpg"
    image randybeachsandywank02 = "Day1/randybeachsandywank02.jpg"
    image beach = "Day1/beach.jpg"
    image ryancomputer = "Day1/ryancomputer.jpg"
    image ryancomputergame = "Day1/ryancomputergame.jpg"
    image ryancomputergameday = "Day1/ryancomputergameday.jpg"
    image ryancomputerday = "Day1/ryancomputerday.jpg"
    image bathroomdoorclosed = "Day1/bathroomdoorclosed.jpg"
    image bathroomdooropen = "Day1/bathroomdooropen.jpg"
    image nancybedroomclosed = "Day1/nancybedroomclosed.jpg"
    image stats = "Day1/stats.jpg"
    image chiyobeach01 = "Day1/chiyobeach01.jpg"
    image chiyobeach02 = "Day1/chiyobeach02.jpg"
    image chiyobeach03 = "Day1/chiyobeach03.jpg"
    image chiyobeach03 = "Day1/chiyobeach03.jpg"
    image chiyobeach04 = "Day1/chiyobeach04.jpg"
    image chiyobeach05 = "Day1/chiyobeach05.jpg"
    image chiyolotion = "Day1/chiyolotion.jpg"
    image poolnikki01 = "Day1/poolnikki01.jpg"
    image poolnikki02 = "Day1/poolnikki02.jpg"
    image nikkibedroomhelp = "Day1/nikkibedroomhelp.jpg"
    image nikkibedroomhelpbed = "Day1/nikkibedroomhelpbed.jpg"
    image nikkibedroomhelpdresser = "Day1/nikkibedroomhelpdresser.jpg"
    image busdrive = "Day1/busdrive.jpg"
    image poolempty = "Day1/poolempty.jpg"

    image plane01 = "Day1/plane01.jpg"
    image plane02 = "Day1/plane02.jpg"
    image plane03 = "Day1/plane03.jpg"
    image plane04 = "Day1/plane04.jpg"
    image jetlanding = "Day1/jetlanding.jpg"
    image house01 = "Day1/house01.jpg"
    image decision = "Day1/decision.jpg"
    image hostessfuckcum = "Day1/hostessfuckcum.jpg"
    image hostessfuckcum01 = "Day1/hostessfuckcum01.jpg"
    image hostessblowcum = "Day1/hostessblowcum.jpg"
    image hostessblowcum01 = "Day1/hostessblowcum01.jpg"
    image housepool01 = "Day1/housepool01.jpg"
    image dinner01 = "Day1/dinner01.jpg"
    image tiniwini01 = "Day1/tiniwini01.jpg"
    image adebby01 = "Day1/adebby01.jpg"
    image adebby02 = "Day1/adebby02.jpg"
    image adebby03 = "Day1/adebby03.jpg"
    image black = "Day1/blackscreen.jpg"
    image housepoolempty = "Day1/housepoolempty.jpg"
    image shower = "Day1/shower.jpg"
    image beachchallenger01 = "Day1/beachchallenger01.jpg"
    image beachchallenger02 = "Day1/beachchallenger02.jpg"
    image beachchallenger01b = "Day1/beachchallenger01b.png"
    image beachchallenger01c = "Day1/beachchallenger01c.png"
    image beachchallengernikki = "Day1/beachchallengernikki.png"
    image beachchallengernikki01 = "Day1/beachchallengernikki01.jpg"
    image beachchallengernikki02 = "Day1/beachchallengernikki02.jpg"
    image beachchallengernikki03 = "Day1/beachchallengernikki03.jpg"
    image beachchallengernikki04 = "Day1/beachchallengernikki04.jpg"
    image beachchallengernikki05 = "Day1/beachchallengernikki05.jpg"
    image beachmeet01 = "Day1/beachmeet01.jpg" 
    image beachmeet02 = "Day1/beachmeet02.jpg" 
    image beachmeet03 = "Day1/beachmeet03.jpg"     
    image beachmeet04 = "Day1/beachmeet04.jpg"     
    image beachnancydrink = "Day1/beachnancydrink.jpg"     
    image beachnancydrunk = "Day1/beachnancydrunk.jpg"     
    image nikkilotion01 = "Day1/nikkilotion01.jpg"     
    image nikkilotion02 = "Day1/nikkilotion02.jpg"     
    image nikkilotion03 = "Day1/nikkilotion03.jpg"     
    image nikkilotion04 = "Day1/nikkilotion04.jpg"     
    image nikkilotionbad = "Day1/nikkilotionbad.jpg"     
    image nikkilotionhappy = "Day1/nikkilotionhappy.jpg"     
    image debbybikini01 = "Day1/debbybikini01.png"
    image debbybikini02 = "Day1/debbybikini02.png"
    image debbybikini03 = "Day1/debbybikini03.png"
    image debbybikini04 = "Day1/debbybikini04.png"
    image nancybikini01 = "Day1/nancybikini01.png"
    image nancybikini02 = "Day1/nancybikini02.png"
    image nancybikini03 = "Day1/nancybikini03.png"
    image nancybikini04 = "Day1/nancybikini04.png"
    image nikkicrying = "Day1/nikkicrying.png"
    image nikkihappy = "Day1/nikkihappy.png"
    image nikkiunpacking = "Day1/nikkiunpacking.png"
    image tiniwiniryannancy = "Day1/tiniwiniryannancy.png"
    image tiniwiniryannikki = "Day1/tiniwiniryannikki.png"
    image beachnancysprite = "Day1/beachnancysprite.png"

# Day2 images

    image nancyyoga01 = "Day2/nancyyoga01.jpg"
    image nancyyoga02 = "Day2/nancyyoga02.jpg"
    image nancyyoga03 = "Day2/nancyyoga03.jpg"
    image nancyyoga04 = "Day2/nancyyoga04.jpg"
    image nancyyogaryan01 = "Day2/nancyyogaryan01.jpg"
    image nancyyogaryan02 = "Day2/nancyyogaryan02.jpg"    
    image ryantv = "Day2/ryantv.jpg"
    image nikkishowermorning01 = "Day2/nikkishowermorning01.jpg"
    image nikkishowermorning02 = "Day2/nikkishowermorning02.jpg"
    image ryanjog01 = "Day2/ryanjog01.jpg"
    image ryanjog02 = "Day2/ryanjog02.jpg"
    image ryanjog03 = "Day2/ryanjog03.jpg"
    image ryanjog04 = "Day2/ryanjog04.jpg"
    image ryanjog05 = "Day2/ryanjog05.jpg"
    image morninglate = "Day2/morninglate.jpg"
    image breakfast02 = "Day2/breakfast02.jpg"
    image breakfast02b = "Day2/breakfast02b.png"
    image breakfast02c = "Day2/breakfast02c.png"
    image breakfast02d = "Day2/breakfast02d.png"
    image breakfast02e = "Day2/breakfast02e.png"
    image quentingreet = "Day2/quentingreet.jpg"
    image classmeet01 = "Day2/classmeet01.jpg"
    image classmeet02 = "Day2/classmeet02.jpg"
    image classmeet03 = "Day2/classmeet03.jpg"
    image classmeet04 = "Day2/classmeet04.jpg"
    image classmeet05 = "Day2/classmeet05.jpg"
    image classmeet06 = "Day2/classmeet06.jpg"
    image lesson01 = "Day2/lesson01.jpg"
    image laurasmile = "Day2/laurasmile.png"
    image lesson01b = "Day2/lesson01b.png"
    image lesson01c = "Day2/lesson01c.png"
    image classroomdreaming01 = "Day2/classroomdreaming01.jpg"
    image classroomdreaming02 = "Day2/classroomdreaming02.jpg"
    image classroomdreaming03 = "Day2/classroomdreaming03.jpg"
    image classroomarrival = "Day2/classroomarrival.jpg"
    image classintro = "Day2/classintro.jpg"    
    image locker = "Day2/locker.jpg"
    image goth01 = "Day2/goth01.jpg"
    image goth01b = "Day2/goth01b.jpg"
    image goth01c = "Day2/goth01c.png"
    image goth01d = "Day2/goth01d.png"
    image principal01 = "Day2/principal01.jpg"
    image principal02 = "Day2/principal02.jpg"
    image principal03 = "Day2/principal03.jpg"
    image principal04 = "Day2/principal04.jpg"
    image principal05 = "Day2/principal05.jpg"
    image principal06 = "Day2/principal06.jpg"
    image principal07 = "Day2/principal07.jpg"
    image principal08 = "Day2/principal08.jpg"
    image principal09 = "Day2/principal09.jpg"
    image principal10 = "Day2/principal10.jpg"
    image principal11 = "Day2/principal11.jpg"
    image principal12 = "Day2/principal12.jpg"
    image principal12b = "Day2/principal12b.jpg"
    image lockerkate01 = "Day2/lockerkate01.jpg"    
    image lockerkate02 = "Day2/lockerkate02.jpg"    
    image lockerkate03 = "Day2/lockerkate03.jpg"    
    image lockerkate04 = "Day2/lockerkate04.jpg"    
    image lockerkate04black = "Day3/lockerkate04black.jpg"    
    image lockerkate05 = "Day2/lockerkate05.jpg"    
    image lockerkate06 = "Day2/lockerkate06.jpg"    
    image lockerkate07 = "Day2/lockerkate07.jpg"
    image lockerbritmovie = "Day2/lockerbritmovie.jpg"
    image lockerbrit01 = "Day2/lockerbrit01.jpg"
    image lockerbrit02 = "Day2/lockerbrit02.jpg"
    image lockerbrit02b = "Day2/lockerbrit02b.png"
    image lockerbrit02c = "Day2/lockerbrit02c.png"
    image lockerbrit02d = "Day2/lockerbrit02d.png"
    image nikkichantelle01 = "Day2/nikkichantelle01.jpg"
    image nikkichantelle01b = "Day2/nikkichantelle01b.png"
    image nikkichantelle01c = "Day2/nikkichantelle01c.png"
    image nikkichantelle01d = "Day2/nikkichantelle01d.png"
    image nikkichantelle01e = "Day2/nikkichantelle01e.png"
    image schoolgymempty = "Day2/schoolgymempty.jpg"
    image schoolgymworkout01 = "Day2/schoolgymworkout01.jpg"
    image schoolgymworkout02 = "Day2/schoolgymworkout02.jpg"
    image schoolgymworkout03 = "Day2/schoolgymworkout03.jpg"
    image chantellegym01 = "Day2/chantellegym01.jpg"
    image chantellegym02 = "Day2/chantellegym02.jpg"
    image chantellegym03 = "Day2/chantellegym03.jpg"
    image chantellegym04a = "Day2/chantellegym04a.jpg"
    image chantellegym04b = "Day2/chantellegym04b.jpg"
    image chantellegym05a = "Day2/chantellegym05a.jpg"
    image chantellegym05b = "Day2/chantellegym05b.jpg"
    image chantellegym06a = "Day2/chantellegym06a.jpg"
    image chantellegym06b = "Day2/chantellegym06b.jpg"
    image chantellegym06c = "Day2/chantellegym06c.jpg"
    image chantellegymkiss = "Day2/chantellegymkiss.jpg"    
    image maddygym01 = "Day2/maddygym01.jpg"
    image maddygym02 = "Day2/maddygym02.jpg"
    image maddygym03 = "Day2/maddygym03.jpg"
    image maddygym04 = "Day2/maddygym04.jpg"
    image maddygym05 = "Day2/maddygym05.jpg"
    image maddygym06 = "Day2/maddygym06.jpg"
    image maddygym07 = "Day2/maddygym07.jpg"
    image detention01 = "Day2/detention01.jpg"
    image katedreaming01 = "Day2/katedreaming01.jpg"
    image katedreaming02 = "Day2/katedreaming02.jpg"
    image katedreaming03 = "Day2/katedreaming03.jpg"
    image lollybeach01 = "Day2/lollybeach01.jpg"
    image lollybeach02 = "Day2/lollybeach02.jpg"
    image lollybeach03 = "Day2/lollybeach03.jpg"
    image lollybeach04 = "Day2/lollybeach04.jpg"
    image lollybeach04b = "Day2/lollybeach04b.png"
    image lollybeachcop01 = "Day2/lollybeachcop01.jpg"
    image lollybeachcop02 = "Day2/lollybeachcop02.jpg"
    image lollybeachmariaangry01 = "Day2/lollybeachmariaangry01.jpg"
    image lollybeachmariaangry02 = "Day2/lollybeachmariaangry02.jpg"
    image mariagrateful = "Day2/mariagrateful.jpg"
    image mariasorry = "Day2/mariasorry.jpg"
    image mariahappy = "Day2/mariahappy.jpg"
    image mariaangry = "Day2/mariaangry.jpg"
    image jail01 = "Day2/jail01.jpg"
    image jail02 = "Day2/jail02.jpg"
    image jail03 = "Day2/jail03.jpg"
    image jailmom01 = "Day2/jailmom01.jpg"
    image jailmom01b = "Day2/jailmom01b.png"
    image hallebikini01 = "Day2/hallebikini01.jpg"
    image hallebikini02 = "Day2/hallebikini02.jpg"
    image hallechange = "Day2/hallechange.jpg"
    image hallegift = "Day2/hallegift.jpg"
    image halleshop01 = "Day2/halleshop01.jpg"
    image halleshop01b = "Day2/halleshop01b.png"
    image halletopoff = "Day2/halletopoff.jpg"
    image lesbians01 = "Day2/lesbians01.jpg"
    image lesbians01b = "Day2/lesbians01b.png"
    image lesbians02 = "Day2/lesbians02.jpg"
    image lesbians03 = "Day2/lesbians03.jpg"
    image lesbian01happy = "Day2/lesbian01happy.png"
    image lesbian02happy = "Day2/lesbian02happy.png"
    image lesbians04 = "Day2/lesbians04.jpg"
    image lesbianscum = "Day2/lesbianscum.jpg"
    image lesbianscum02 = "Day2/lesbianscum02.jpg"
    image lesbianscum02b = "Day2/lesbianscum02b.jpg"
    image lesbiansbeaten = "Day2/lesbiansbeaten.jpg"
    image randyanna01 = "Day2/randyanna01.jpg"
    image randyanna02 = "Day2/randyanna02.jpg"
    image randyanna03 = "Day2/randyanna03.jpg"
    image randyanna04 = "Day2/randyanna04.jpg"
    image randyanna05 = "Day2/randyanna05.jpg"
    image randyanna06 = "Day2/randyanna06.jpg"
    image randyanna07 = "Day2/randyanna07.jpg"
    image randyanna08 = "Day2/randyanna08.jpg"
    image randyannaryan01 = "Day2/randyannaryan01.jpg"
    image shop = "Day2/shop.jpg"
    image shop01 = "Day2/shop01.jpg"
    image shop02 = "Day2/shop02.jpg"
    image shop03 = "Day2/shop03.jpg"
    image store01 = "Day2/store01.jpg"
    image store02 = "Day2/store02.jpg"
    image store03 = "Day2/store03.jpg"
    image store04 = "Day2/store04.jpg"
    image store05 = "Day2/store05.jpg"
    image store06 = "Day2/store06.jpg"
    image store07 = "Day2/store07.jpg"
    image storage = "Day2/storage.jpg"
    image storageladder = "Day2/storageladder.jpg"
    image storagefall = "Day2/storagefall.jpg"
    image storagecatchfrancine = "Day2/storagecatchfrancine.jpg"
    image storagecatchbeer = "Day2/storagecatchbeer.jpg"
    image storageclean = "Day2/storageclean.jpg"
    image storeteagan01 = "Day2/storeteagan01.jpg"
    image storeteagan02 = "Day2/storeteagan02.jpg"
    image storeteagan03 = "Day2/storeteagan03.jpg"
    image storeteagan04 = "Day2/storeteagan04.jpg"
    image storeteagan05 = "Day2/storeteagan05.jpg"
    image storeteagan06 = "Day2/storeteagan06.jpg"
    image storepark01 = "Day2/storepark01.jpg"
    image storeteaganhide = "Day2/storeteaganhide.jpg"
    image storepark02 = "Day2/storepark02.jpg"
    image storepark03 = "Day2/storepark03.jpg"
    image debbyhouse01 = "Day2/debbyhouse01.jpg"
    image debbyhouse02 = "Day2/debbyhouse02.jpg"
    image debbyhouse03 = "Day2/debbyhouse03.jpg"
    image debbyhouse04 = "Day2/debbyhouse04.jpg"
    image debbysnooping = "Snooping/debbysnooping.jpg"
    image debbyhousebikini01 = "Day2/debbyhousebikini01.jpg"
    image debbyhousebikini02 = "Day2/debbyhousebikini02.jpg"
    image debbyhousebikini03 = "Day2/debbyhousebikini03.jpg"
    image debbyhousebikini04 = "Day2/debbyhousebikini04.jpg"
    image debbyhousebikini05 = "Day2/debbyhousebikini05.jpg"
    image debbyhousebikini06 = "Day2/debbyhousebikini06.jpg"
    image debbycar01 = "Day2/debbycar01.jpg"
    image debbycar02 = "Day2/debbycar02.jpg"
    image debbycar03 = "Day2/debbycar03.jpg"
    image debbycar04 = "Day2/debbycar04.jpg"
    image debbycar05 = "Day2/debbycar05.jpg"
    image debbystairway = "Day2/debbystairway.jpg"
    image debbybedroom01 = "Day2/debbybedroom01.jpg"
    image debbybedroom02 = "Day2/debbybedroom02.jpg"
    image debbybedroom03 = "Day2/debbybedroom03.jpg"
    image debbybedroom04 = "Day2/debbybedroom04.jpg"
    image debbybedroom05 = "Day2/debbybedroom05.jpg"
    image debbycockslap01 = "Day2/debbycockslap01.jpg"
    image debbycockslap02 = "Day2/debbycockslap02.jpg"
    image debbyarseslap01 = "Day2/debbyarseslap01.jpg"
    image debbyarseslap02 = "Day2/debbyarseslap02.jpg"
    image nurse01 = "Day2/nurse01.jpg"
    image nurse02 = "Day2/nurse02.jpg"
    image nurse03 = "Day2/nurse03.jpg"
    image nurse04 = "Day2/nurse04.jpg"
    image nurse05 = "Day2/nurse05.jpg"
    image nurse06 = "Day2/nurse06.jpg"
    image nurse07 = "Day2/nurse07.jpg"
    image nurse08 = "Day2/nurse08.jpg"
    image nurse09 = "Day2/nurse09.jpg"
    image nurse10 = "Day2/nurse10.jpg"
    image nurse11 = "Day2/nurse11.jpg"
    image nurse12 = "Day2/nurse12.jpg"
    image nurse13a = "Day2/nurse13a.jpg"
    image nurse13b = "Day2/nurse13b.jpg"
    image nurse14 = "Day2/nurse14.jpg"
    image nurse15 = "Day2/nurse15.jpg"
    image nurse16 = "Day2/nurse16.jpg"
    image nursesnooping = "Snooping/nursesnooping.jpg"
    image mombedroomsnooping = "Snooping/mombedroomsnooping.jpg"
    image lunch01 = "Day2/lunch01.jpg"
    image lunch02 = "Day2/lunch02.jpg"
    image lunch02sit = "Day2/lunch02sit.jpg"
    image lunchfrieda = "Day2/lunchfrieda.jpg"
    image lunchquentinsad = "Day2/lunchquentinsad.jpg"
    image lunchkatehappy = "Day2/lunchkatehappy.png"
    image lunchkateunhappy = "Day2/lunchkateunhappy.png"
    image lunchlaura = "Day2/lunchlaura.png"    
    image lunchmaddy = "Day2/lunchmaddy.png"
    image lunchchantelle01 = "Day2/lunchchantelle01.png"
    image lunchchantelle02 = "Day2/lunchchantelle02.png"
    image lunchjose01 = "Day2/lunchjose01.png"
    image lunchjose02 = "Day2/lunchjose02.png"
    image lunchjose03 = "Day2/lunchjose03.jpg"
    image lunchjose04 = "Day2/lunchjose04.png"
    image lunchjose05 = "Day2/lunchjose05.png"
    image lunchbrittanny01 = "Day2/lunchbrittany01.png"
    image lunchbrittanny02 = "Day2/lunchbrittany02.png"
    image lunchnikki01 = "Day2/lunchnikki01.png"
    image lunchnikki02 = "Day2/lunchnikki02.png"
    image lunchnikki03 = "Day2/lunchnikki03.png"
    image lunchnikki04 = "Day2/lunchnikki04.jpg"
    image lunchsister01 = "Day2/lunchsister01.jpg"
    image lunchsister02 = "Day2/lunchsister02.jpg"
    image downtown01 = "Day2/downtown01.jpg"
    image downtownaudacious = "Day2/downtownaudacious.jpg"
    image audaciousentrance = "Day2/audaciousentrance.jpg"    
    image audaciousbeaten = "Day2/audaciousbeaten.jpg"
    image security01 = "Day2/security01.png"
    image security01b = "Day2/security01b.png"
    image security02 = "Day2/security02.png"
    image security03 = "Day2/security03.png"
    image oldwomanbus01 = "Day2/oldwomanbus01.jpg"
    image oldwomanbus02 = "Day2/oldwomanbus02.jpg"
    image oldwomanbus03 = "Day2/oldwomanbus03.jpg"
    image detention01 = "Day2/detention01.jpg"
    image friedalibrary01 = "Day2/friedalibrary01.jpg"
    image friedalibrary02 = "Day2/friedalibrary02.jpg"
    image friedalibrary02b = "Day2/friedalibrary02b.png"
    image friedalibrary02c = "Day2/friedalibrary02c.png"
    image friedalibrary02d = "Day2/friedalibrary02d.png"
    image ryanreadinglibrary = "Day2/ryanreadinglibrary.jpg"
    image ryanlibraryinternet = "Day2/ryanlibraryinternet.jpg"
    image parlour01 = "Day2/parlour01.jpg"
    image parlour02 = "Day2/parlour02.jpg"
    image parlour03 = "Day2/parlour03.jpg"
    image parlour03b = "Day2/parlour03b.jpg"
    image parlour04 = "Day2/parlour04.jpg"
    image parlour05 = "Day2/parlour05.jpg"
    image parlour06a = "Day2/parlour06a.jpg"
    image parlour06b = "Day2/parlour06b.jpg"
    image parlour06c = "Day2/parlour06c.jpg"
    image parlour06cum = "Day2/parlour06cum.jpg"
    image parlour07 = "Day2/parlour07.jpg"
    image parlour08 = "Day2/parlour08.jpg"
    image parlour09 = "Day2/parlour09.jpg"
    image parlour10 = "Day2/parlour10.jpg"
    image parlourcum01 = "Day2/parlourcum01.jpg"
    image parlourcum02 = "Day2/parlourcum02.jpg"
    image nikkinormal = "Day2/nikkinormal.png"
    image nancyshocked = "Day2/nancyshocked.png"
    image nancyangry = "Day2/nancyangry.png"
    image nancyhappy = "Day2/nancyhappy.png"
    image nancynikki = "Day2/nancynikki.png"
    image nikkimom = "Day2/nikkimom.png"
    image nikkiryan = "Day2/nikkiryan.png"
    image nikkibedroomhelpdresserwin = "Day2/nikkibedroomhelpdresserwin.jpg"
    image nikkibedroomearring = "Day2/nikkibedroomearring.jpg"
    image nikkibedroomhappy = "Day2/nikkibedroomhappy.jpg"
    image nikkibedroomkiss = "Day2/nikkibedroomkiss.jpg"
    image nikkibedroomhypno = "Day2/nikkibedroomhypno.jpg"
    image nikkibedroomsultry = "Day2/nikkibedroomsultry.jpg"
    image nikkibedroompheromone = "Day2/nikkibedroompheromone.jpg"
    image nikkiundress01 = "Day2/nikkiundress01.jpg"
    image nikkiundress02 = "Day2/nikkiundress02.jpg"
    image nikkiundress03 = "Day2/nikkiundress03.jpg"
    image nikkilick01 = "Day2/nikkilick01.jpg"
    image nikkiblowjob01 = "Day2/nikkiblowjob01.jpg"
    image nikkiblowjob02 = "Day2/nikkiblowjob02.jpg"
    image nikkiblowjobcum01 = "Day2/nikkiblowjobcum01.jpg"
    image nikkiblowjobcum02 = "Day2/nikkiblowjobcum02.jpg"
    image nikkianal01 = "Day2/nikkianal01.jpg"
    image nikkifuckcum01 = "Day2/nikkifuckcum01.jpg"
    image nikkifuckcum02 = "Day2/nikkifuckcum02.jpg"
    image nancyundressing01 = "Day2/nancyundressing01.jpg"
    image nancyundressing02 = "Day2/nancyundressing02.jpg"
    image nancyundressing03 = "Day2/nancyundressing03.jpg"
    image nancyundressing04 = "Day2/nancyundressing04.jpg"
    image nancyundressing05 = "Day2/nancyundressing05.jpg"
    image nancyundressing06 = "Day2/nancyundressing06.jpg"
    image nancyundressing06b = "Day2/nancyundressing06b.jpg"
    image nancyundressing06c = "Day2/nancyundressing06c.jpg"
    image nancyundressing07 = "Day2/nancyundressing07.jpg"
    image nancyundressing08a = "Day2/nancyundressing08a.jpg"
    image nancyundressing08b = "Day2/nancyundressing08b.jpg"
    image nancyundressing08c = "Day2/nancyundressing08c.jpg"
    image williecorridor = "Day2/williecorridor.jpg"
    image poolnikkiday02 = "Day2/poolnikkiday02.jpg"
    image poolryanday02 = "Day2/poolryanday02.jpg"
    image nikkishower01 = "Day2/nikkishower01.jpg"
    image nikkishower02 = "Day2/nikkishower02.jpg"
    image nancyshower01 = "Day2/nancyshower01.jpg"
    image nancyshower02 = "Day2/nancyshower02.jpg"
    image nancyshower03 = "Day2/nancyshower03.jpg"
    
# Day3 images

    image breakfastday03a = "Day3/breakfastday03a.jpg"
    image breakfastday03ablack = "Day3/breakfastday03ablack.png"
    image breakfastday03b = "Day3/breakfastday03b.png"
    image breakfastday03c = "Day3/breakfastday03c.png"
    image breakfastday03d = "Day3/breakfastday03d.png"
    image breakfastday03e = "Day3/breakfastday03e.png"
    image breakfastday03f = "Day3/breakfastday03f.png"


    image audaciousbeatenblack = "Day3/audaciousbeatenblack.jpg"
    image ryanlibrayinternetblack = "Day3/ryanlibrayinternetblack.jpg"
    image ryanreadinglibraryblack = "Day3/ryanreadinglibraryblack.jpg"
    image debbyentranceblack = "Day3/debbyentranceblack.jpg"
    image morninglateday03 = "Day3/morninglateday03.jpg"
    
    image class01day03 = "Day3/class01day03.jpg"
    image classroom01day03 = "Day3/classroom01day03.jpg"
    image classroom02day03 = "Day3/classroom02day03.jpg"
    image classroom03day03 = "Day3/classroom03day03.jpg"
    image classroom04day03 = "Day3/classroom04day03.jpg"
    image classroom05day03 = "Day3/classroom05day03.jpg"
    image classkate01day03 = "Day3/classkate01day03.jpg"
    image classkate02day03 = "Day3/classkate02day03.jpg"
    image classkate03day03 = "Day3/classkate03day03.jpg"
    image classmeetfriedaday03 = "Day3/classmeetfriedaday03.jpg"
    image classmeetmaddyday03 = "Day3/classmeetmaddyday03.jpg"

    image dreamingfriedamaddy01 = "Day3/dreamingfriedamaddy01.jpg"
    image dreamingfriedamaddy02 = "Day3/dreamingfriedamaddy02.jpg"
    image dreamingfriedamaddy03 = "Day3/dreamingfriedamaddy03.jpg"
    image dreaminglaura01 = "Day3/dreaminglaura01.jpg"
    image dreaminglaura02 = "Day3/dreaminglaura02.jpg"
    image dreaminglaura03 = "Day3/dreaminglaura03.jpg"
    
    image secretary01 = "Day3/secretary01.jpg"
    image secretary02 = "Day3/secretary02.jpg"
    image secretary03 = "Day3/secretary03.jpg"
    image secretary04 = "Day3/secretary04.jpg"
    image secretary05 = "Day3/secretary05.jpg"
    image secretary06 = "Day3/secretary06.jpg"
    image debbyoffice01 = "Day3/debbyoffice01.jpg"
    image debbyoffice02 = "Day3/debbyoffice02.jpg"
    image debbyoffice03 = "Day3/debbyoffice03.jpg"
    image debbyoffice04 = "Day3/debbyoffice04.jpg"
    image debbyoffice05 = "Day3/debbyoffice05.jpg"
    image debbyoffice06 = "Day3/debbyoffice06.jpg"
    image debbyoffice07 = "Day3/debbyoffice07.jpg"
    image debbyoffice08 = "Day3/debbyoffice08.jpg"
    image debbyoffice08black = "Day3/debbyoffice08black.jpg"
    image momwork01 = "Day3/momwork01.jpg"
    image momofficeempty = "Day3/momofficeempty.jpg"
    image shoot01 = "Day3/shoot01.jpg"
    image shoot02 = "Day3/shoot02.jpg"
    image shoot03 = "Day3/shoot03.jpg"
    image shoot04 = "Day3/shoot04.jpg"
    image shoot05 = "Day3/shoot05.jpg"
    image shoot06 = "Day3/shoot06.jpg"
    image shoot07 = "Day3/shoot07.jpg"
    image shoot08 = "Day3/shoot08.jpg"
    image shoot09 = "Day3/shoot09.jpg"
    image shoot10 = "Day3/shootfuck10.jpg"
    image shoot11 = "Day3/shootfuck11.jpg"
    image shoot12 = "Day3/shootfuck12.jpg"
    image shoot13 = "Day3/shootfuck13.jpg"
    image shoot14 = "Day3/shootfuck14.jpg"
    image shoot15 = "Day3/shootfuck15.jpg"
    image shootend = "Day3/shootend.jpg"

    image sportshall01 = "Day3/sportshall01.jpg"
    image sportshall02 = "Day3/sportshall02.jpg"
    image sportshall03 = "Day3/sportshall03.jpg"
    image sportshall04 = "Day3/sportshall04.jpg"

    image lunchday03 = "Day3/lunchday03.jpg"
    image lunchday03b = "Day3/lunchday03b.jpg"
    image lunchfriedaday03 = "Day3/lunchfriedaday03.jpg"
    image lunchmaddyhappy = "Day3/lunchmaddyhappy.jpg"
    image lunchquentinhappy = "Day3/lunchquentinhappy.jpg"
    
    image rooftop01 = "Day3/rooftop01.jpg"
    image rooftop02 = "Day3/rooftop02.jpg"
    image rooftop02black = "Day3/rooftop02black.jpg"
    image voyeur01 = "Day3/voyeur01.jpg"
    image voyeur02 = "Day3/voyeur02.jpg"
    image voyeur03 = "Day3/voyeur03.jpg"
    image voyeur04 = "Day3/voyeur04.jpg"
    image voyeur05 = "Day3/voyeur05.jpg"
    image voyeur06 = "Day3/voyeur06.jpg"

    image beachempty = "Day3/beachempty.jpg"
    image hallebeach01 = "Day3/hallebeach01.jpg"
    image hallebeach02 = "Day3/hallebeach02.jpg"
    image hallebeach03 = "Day3/hallebeach03.jpg"
    image hallebeach04 = "Day3/hallebeach04.jpg"
    image hallebeachhypno = "Day3/hallebeachhypno.jpg"
    image hallesea01 = "Day3/hallesea01.jpg"
    image hallesea02 = "Day3/hallesea02.jpg"
    image hallesea03 = "Day3/hallesea03.jpg"
    image hallesea04 = "Day3/hallesea04.jpg"
    image hallefuck01 = "Day3/hallefuck01.jpg"
    image hallefuck02 = "Day3/hallefuck02.jpg"
    image hallefuck03 = "Day3/hallefuck03.jpg"
    image hallefuck04 = "Day3/hallefuck04.jpg"
    image hallefuck05 = "Day3/hallefuck05.jpg"
    image hallefuckcum01 = "Day3/hallefuckcum01.jpg"
    image hallefuckcum02 = "Day3/hallefuckcum02.jpg"
    image hallefuckcum03 = "Day3/hallefuckcum03.jpg"

    image beachswim01 = "Day3/beachswim01.jpg"
    image beachswim02 = "Day3/beachswim02.jpg"
    image underwater01 = "Day3/underwater01.jpg"
    image underwater02 = "Day3/underwater02.jpg"
    image underwater03 = "Day3/underwater03.jpg"
    image underwater03b = "Day3/underwater03b.jpg"
    image underwater04 = "Day3/underwater04.jpg"
    image underwater05 = "Day3/underwater05.jpg"
    image mermaid01 = "Day3/mermaid01.jpg"
    image mermaid02 = "Day3/mermaid02.jpg"
    image mermaid03 = "Day3/mermaid03.jpg"
    image mermaid04 = "Day3/mermaid04.jpg"
    image mermaid05 = "Day3/mermaid05.jpg"
    image mermaid06 = "Day3/mermaid06.jpg"
    image mermaid07 = "Day3/mermaid07.jpg"
    image mermaid08 = "Day3/mermaid08.jpg"
    image mermaid09 = "Day3/mermaid09.jpg"
    image mermaid10 = "Day3/mermaid10.jpg"
    image mermaid11 = "Day3/mermaid11.jpg"
    image mermaid12 = "Day3/mermaid12.jpg"
    image baba01 = "Day3/baba01.jpg"
    image baba02 = "Day3/baba02.jpg"
    image fatguyparasol01 = "Day3/fatguyparasol01.jpg"
    image fatguyparasol02 = "Day3/fatguyparasol02.jpg"
    image fatguyparasol03 = "Day3/fatguyparasol03.jpg"
    
    image gym01 = "Day3/gym01.jpg"
    image gym02 = "Day3/gym02.jpg"
    image gym03 = "Day3/gym03.jpg"
    image gym04 = "Day3/gym04.jpg"
    image gym05 = "Day3/gym05.jpg"
    image gym06 = "Day3/gym06.jpg"
    
    image katehouse01 = "Day3/katehouse01.jpg"
    image katehouse02 = "Day3/katehouse02.jpg"
    image katehouse03 = "Day3/katehouse03.jpg"
    image katepool01 = "Day3/katepool01.jpg"
    image katepool02 = "Day3/katepool02.jpg"
    image katepool03 = "Day3/katepool03.jpg"
    image katepool04 = "Day3/katepool04.jpg"
    image katepool05 = "Day3/katepool05.jpg"
    image katepool06 = "Day3/katepool06.jpg"
    image katepool07 = "Day3/katepool07.jpg"
    image katepool07b = "Day3/katepool07b.jpg"
    image katepool08 = "Day3/katepool08.jpg"
    image katepool09 = "Day3/katepool09.jpg"
    image katepool10 = "Day3/katepool10.jpg"
    image katepool11 = "Day3/katepool11.jpg"
    image katepool12 = "Day3/katepool12.jpg"
    image katepool13 = "Day3/katepool13.jpg"
    image katepool14 = "Day3/katepool14.jpg"
    image katepool15 = "Day3/katepool15.jpg"
    image katepool16a = "Day3/katepool16a.jpg"
    image katepool16b = "Day3/katepool16b.jpg"
    image katepool17 = "Day3/katepool17.jpg"
    image katepool18 = "Day3/katepool18.jpg"
    image katepool19 = "Day3/katepool19.jpg"
    image katepoolwank01 = "Day3/katepoolwank01.jpg"
    image katepoolwank01b = "Day3/katepoolwank01b.jpg"
    image katepoolcum01 = "Day3/katepoolcum01.jpg"
    image katepoolcum02 = "Day3/katepoolcum02.jpg"
    image katepoolcum03 = "Day3/katepoolcum03.jpg"
    image katepoolend = "Day3/katepoolend.jpg"

    image willie02 = "Day3/willie02.jpg"
    image willie02b = "Day3/willie02b.png"
    image willie02c = "Day3/willie02c.png"
    image willie03 = "Day3/willie03.jpg"
    image willie04 = "Day3/willie04.jpg"
    image principalback01 = "Day3/principalback01.jpg"
    
    image guidance01 = "Day3/guidance01.jpg"
    image guidance02 = "Day3/guidance02.jpg"
    image guidance03 = "Day3/guidance03.jpg"
    image guidance04 = "Day3/guidance04.jpg"
    image guidancecum01 = "Day3/guidancecum01.jpg"
    image guidancecum02 = "Day3/guidancecum02.jpg"
    
    image schoolbathroom01 = "Day3/schoolbathroom01.jpg"
    image schoolbathroom02 = "Day3/schoolbathroom02.jpg"
    image schoolbathroom03 = "Day3/schoolbathroom03.jpg"
    image schoolbathroombrittany01 = "Day3/schoolbathroombrittany01.jpg"
    image schoolbathroombrittany02 = "Day3/schoolbathroombrittany02.jpg"
    image schoolbathroombrittany02b = "Day3/schoolbathroombrittany02b.jpg"
    image schoolbathroombrittany02c = "Day3/schoolbathroombrittany02c.jpg"
    image schoolbathroombrittany02d = "Day3/schoolbathroombrittany02d.jpg"
    image schoolbathroombrittany03 = "Day3/schoolbathroombrittany03.jpg"
    image schoolbathroombrittany04 = "Day3/schoolbathroombrittany04.jpg"
    image schoolbathroombrittany05 = "Day3/schoolbathroombrittany05.jpg"
    image schoolbathroombrittany05black = "Day3/schoolbathroombrittany05black.jpg"
    image schoolbathroombrittany06 = "Day3/schoolbathroombrittany06.jpg"
    image schoolbathroombrittany06black = "Day3/schoolbathroombrittany06black.jpg"
    image gloryhole01 = "Day3/gloryhole01.jpg"
    image gloryholend = "Day3/gloryholend.jpg"
    image gloryhole01black = "Day3/gloryhole01black.jpg"
    image gloryholebrit01 = "Day3/gloryholebrit01.jpg"
    image gloryholebrit02 = "Day3/gloryholebrit02.jpg"
    image gloryholebrit03 = "Day3/gloryholebrit03.jpg"
    image gloryholebrit04 = "Day3/gloryholebrit04.jpg"
    image gloryholebrit05 = "Day3/gloryholebrit05.jpg"
    image gloryholebrit06 = "Day3/gloryholebrit06.jpg"
    image gloryholebrit06black = "Day3/gloryholebrit06black.jpg"
    image gloryholebrit07 = "Day3/gloryholebrit07.jpg"
    image brittanycrying01 = "Day3/brittanycrying01.jpg"
    image brittanycrying01b = "Day3/brittanycrying01b.jpg"
    
    image tower01 = "Day3/tower01.jpg"
    image tower02 = "Day3/tower02.jpg"
    image tower03 = "Day3/tower03.jpg"
    image tower04 = "Day3/tower04.jpg"
    image tower05 = "Day3/tower05.jpg"
    image tower06 = "Day3/tower06.jpg"
    image tower07 = "Day3/tower07.jpg"
    image tower08 = "Day3/tower08.jpg"
    image tower09 = "Day3/tower09.jpg"
    image tower10 = "Day3/tower10.jpg"
    image tower11 = "Day3/tower11.jpg"
    image tower11b = "Day3/tower11b.jpg"
    image towersandy01 = "Day3/towersandy01.jpg"
    image towersandy02 = "Day3/towersandy02.jpg"
    image towersandy03 = "Day3/towersandy03.jpg"
    image towerslolly01 = "Day3/towerlolly01.jpg"
    image towerslolly02 = "Day3/towerlolly02.jpg"
    image towerslolly03 = "Day3/towerlolly03.jpg"
    image arm01 = "Day3/arm01.jpg"
    image arm01b = "Day3/arm01b.jpg"
    image armlost = "Day3/armlost.jpg"
    image armwon = "Day3/armwon.jpg"
    image towerend = "Day3/towerend.jpg"
    image beachbarpamela01 = "Day3/beachbarpamela01.jpg"
    image beachbarpamela02 = "Day3/beachbarpamela02.jpg"
    
    image chiyorandy01 = "Day3/chiyorandy01.jpg"
    image chiyorandy02 = "Day3/chiyorandy02.jpg"
    image chiyorandy03 = "Day3/chiyorandy03.jpg"
    image chiyorandy03b = "Day3/chiyorandy03b.jpg"
    image chiyorandy04 = "Day3/chiyorandy04.jpg"
    image chiyorandy05 = "Day3/chiyorandy05.jpg"
    image chiyorandy06 = "Day3/chiyorandy06.jpg"
    image chiyorandy07 = "Day3/chiyorandy07.jpg"
    image chiyorandy08 = "Day3/chiyorandy08.jpg"
    image chiyorandy09 = "Day3/chiyorandy09.jpg"

    image campfire01 = "Day3/campfire01.jpg"
    image campfire02 = "Day3/campfire02.jpg"
    image campfire03 = "Day3/campfire03.jpg"
    image campfire04 = "Day3/campfire04.jpg"
    image campfire04b = "Day3/campfire04b.png"
    image campfire04c = "Day3/campfire04c.png"
    image campfire05 = "Day3/campfire05.jpg"
    image campfire05b = "Day3/campfire05b.jpg"
    image campfire05c = "Day3/campfire05c.jpg"
    image campfire05d = "Day3/campfire05d.png"
    image campfire06 = "Day3/campfire06.jpg"
    image campfire07 = "Day3/campfire07.jpg"
    image campfire07b = "Day3/campfire07b.jpg"
    image campfire08 = "Day3/campfire08.jpg"
    image campfire09 = "Day3/campfire09.jpg"
    image campfire09b = "Day3/campfire09b.jpg"
    image campfire09c = "Day3/campfire09c.jpg"
    image campfire10 = "Day3/campfire10.jpg"
    image campfire11 = "Day3/campfire11.jpg"
    image campfire12 = "Day3/campfire12.jpg"
    image campfire13 = "Day3/campfire13.jpg"
    image campfire14 = "Day3/campfire14.jpg"
    image campfire15 = "Day3/campfire15.jpg"
    image campfire16 = "Day3/campfire16.jpg"
    image campfire16b = "Day3/campfire16b.jpg"
    image campfiretease01 = "Day3/campfiretease01.jpg"
    image campfiretease02 = "Day3/campfiretease02.jpg"
    image campfiretease03 = "Day3/campfiretease03.jpg"
    image campfiretease04 = "Day3/campfiretease04.jpg"
    image campfiretease05 = "Day3/campfiretease05.jpg"
    image campfiretease06 = "Day3/campfiretease06.jpg"
    image campfirefuckcum01 = "Day3/campfirefuckcum01.jpg"
    image campfirefuckcum02 = "Day3/campfirefuckcum02.jpg"
    image campfirefuckcum03 = "Day3/campfirefuckcum03.jpg"
    image campfirehypno = "Day3/campfirehypno.jpg"
    image campfireforcedkiss = "Day3/campfireforcedkiss.jpg"

    image teaganhouse01 = "Day3/teaganhouse01.jpg"
    image teaganhouse02 = "Day3/teaganhouse02.jpg"
    image teaganhouse03 = "Day3/teaganhouse03.jpg"
    image teaganhouse04 = "Day3/teaganhouse04.jpg"
    image teaganhouse05 = "Day3/teaganhouse05.jpg"
    image teaganhouse06 = "Day3/teaganhouse06.jpg"
    
    image tanyahouse01 = "Day3/tanyahouse01.jpg"
    image tanyahouse02 = "Day3/tanyahouse02.jpg"
    image tanyahouse03 = "Day3/tanyahouse03.jpg"
    image webcam01 = "Day3/webcam01.jpg"
    image webcam02 = "Day3/webcam02.jpg"
    image webcam03 = "Day3/webcam03.jpg"
    image webcam04 = "Day3/webcam04.jpg"
    image webcam05 = "Day3/webcam05.jpg"
    image webcam06 = "Day3/webcam06.jpg"
    image webcam07 = "Day3/webcam07.jpg"
    image webcam08 = "Day3/webcam08.jpg"
    image webcam09 = "Day3/webcam09.jpg"
    image webcam10 = "Day3/webcam10.jpg"
    image webcam11 = "Day3/webcam11.jpg"
    image webcam12 = "Day3/webcam12.jpg"
    image webcam13 = "Day3/webcam13.jpg"
    image webcam14 = "Day3/webcam14.jpg"
    
    image marialibrary01 = "Day3/marialibrary01.jpg"
    image marialibrary02 = "Day3/marialibrary02.jpg"
    image marialibrary03 = "Day3/marialibrary03.jpg"
    image marialibrary04 = "Day3/marialibrary04.jpg"
    image marialibrary05 = "Day3/marialibrary05.jpg"
    image marialibrary06 = "Day3/marialibrary06.jpg"
    image marialibrary07 = "Day3/marialibrary07.jpg"
    image nerdy00 = "Day3/nerdy00.jpg"
    image nerdy01 = "Day3/nerdy01.jpg"
    image nerdy02 = "Day3/nerdy02.jpg"
    image nerdy03 = "Day3/nerdy03.jpg"
    image nerdy04 = "Day3/nerdy04.jpg"
    image nerdy04black = "Day3/nerdy04black.jpg"
    image nerdy05 = "Day3/nerdy05.jpg"
    image nerdy05black = "Day3/nerdy05black.jpg"
    image nerdy06 = "Day3/nerdy06.jpg"
    image nerdy06black = "Day3/nerdy06black.jpg"
    image nerdy07 = "Day3/nerdy07.jpg"
    image nerdy07black = "Day3/nerdy07black.jpg"
    image friedalibrary01day03 = "Day3/friedalibrary01day03.jpg"
    image friedalibrary02day03 = "Day3/friedalibrary02day03.jpg"
    image friedalibrary03day03 = "Day3/friedalibrary03day03.jpg"
    image friedafuck01 = "Day3/friedafuck01.jpg"
    image friedafuck02 = "Day3/friedafuck02.jpg"
    image friedafuck03 = "Day3/friedafuck03.jpg"
    image friedafuck04 = "Day3/friedafuck04.jpg"
    image friedafuck04b = "Day3/friedafuck04b.jpg"
    image friedafuck05 = "Day3/friedafuck05.jpg"
    image friedafuck06 = "Day3/friedafuck06.jpg"
    image friedafuck07 = "Day3/friedafuck07.jpg"
    image friedafuck08 = "Day3/friedafuck08.jpg"
    image friedafuck08b = "Day3/friedafuck08b.jpg"
    image friedafuck09 = "Day3/friedafuck09.jpg"
    image friedafuck10 = "Day3/friedafuck10.jpg"
    image friedafuck10b = "Day3/friedafuck10b.jpg"
    image friedacum01 = "Day3/friedacum01.jpg"
    image friedacum02 = "Day3/friedacum02.jpg"
    
    image ryanconanposing01 = "Day3/ryanconanposing01.jpg"
    image ryanconanposing01b = "Day3/ryanconanposing01b.jpg"
    image ryanconanposing02 = "Day3/ryanconanposing02.jpg"
    image eveningalien = "Day3/eveningalien.jpg"
    image eveningconan = "Day3/eveningconan.jpg"
    image eveningmom01 = "Day3/eveningmom01.jpg"
    image eveningmomconan = "Day3/eveningmomconan.jpg"
    image eveningtvkiss = "Day3/eveningtvkiss.jpg"
    image eveningtvmom01 = "Day3/eveningtvmom01.jpg"
    image eveningmomstrap = "Day3/eveningmomstrap.jpg"
    image eveningmompendulum = "Day3/eveningmompendulum.jpg"
    image eveningmomfuck01 = "Day3/eveningmomfuck01.jpg"
    image momblowjob01 = "Day3/eveningmomfuck02.jpg"
    image momblowjob01b = "Day3/eveningmomfuck02b.jpg"
    image momblowjob02 = "Day3/eveningmomfuck03.jpg"
    image momblowjob03 = "Day3/eveningmomfuck04.jpg"
    image momtitfuckcum01 = "Day3/momtitfuckcum01.jpg"
    image momtitfuckcum02 = "Day3/momtitfuckcum02.jpg"
    image momtitfuck01 = "Day3/eveningmomfuck05.jpg"
    image momtitfuck02 = "Day3/eveningmomfuck06.jpg"
    image eveningmomclit = "Day3/eveningmomclit.jpg"
    image eveningmomready = "Day3/eveningmomready.jpg"
    image momfuckcum01 = "Day3/momfuckcum01.jpg"
    image momfuckcum02 = "Day3/momfuckcum02.jpg"
    image momfuckcum03 = "Day3/momfuckcum03.jpg"
    
    image dorisgym01 = "Day3/dorisgym01.jpg"
    image dorisgym02 = "Day3/dorisgym02.jpg"
    image dorisgym03 = "Day3/dorisgym03.jpg"
    image dorisgym04 = "Day3/dorisgym04.jpg"
    image dorisryangym01 = "Day3/dorisryangym01.jpg"
    image dorissauna01 = "Day3/dorissauna01.jpg"
    image dorissauna02 = "Day3/dorissauna02.jpg"
    image dorissauna03 = "Day3/dorissauna03.jpg"
    image dorissauna04 = "Day3/dorissauna04.jpg"
    image dorissauna05 = "Day3/dorissauna05.jpg"
    image dorissauna05b = "Day3/dorissauna05b.jpg"
    image dorissaunacum01 = "Day3/dorissaunacum01.jpg"
    image dorissaunacum02 = "Day3/dorissaunacum02.jpg"
    image dorissaunacum03 = "Day3/dorissaunacum03.jpg"

    image downtownposter = "Day3/downtownposter.jpg"
    
    image storepacking = "Day3/storepacking.jpg"
    
    image swim01 = "Day3/swim01.jpg"
    image swim02 = "Day3/swim02.jpg"
    image swim03 = "Day3/swim03.jpg"
    image swim04 = "Day3/swim04.jpg"
    image swim05 = "Day3/swim05.jpg"
    image swim06 = "Day3/swim06.jpg"
    image swim07 = "Day3/swim07.jpg"
    image swim08 = "Day3/swim08.jpg"
    image swimfrieda = "Day3/swimfrieda.jpg"
    image swimlaura = "Day3/swimlaura.jpg"
    
    image dinnerday03a = "Day3/dinnerday03a.jpg"
    image dinnerday03ablack = "Day3/dinnerday03ablack.jpg"
    image dinnerday03b = "Day3/dinnerday03b.jpg"
    image dinnerday03bblack = "Day3/dinnerday03bblack.jpg"
    image dinnerday03c = "Day3/dinnerday03c.png"
   
# Day4 images

    image audaciouscop01 = "Day4/audaciouscop01.jpg"
    image audaciouscop02 = "Day4/audaciouscop02.jpg"
    image audaciouscop03 = "Day4/audaciouscop03.jpg"

    image babalesbian01 = "Day4/babalesbian01.jpg"
    image babalesbian02 = "Day4/babalesbian02.jpg"
    image babalesbian03 = "Day4/babalesbian03.jpg"
    image babalesbian04 = "Day4/babalesbian04.jpg"

    image bigdong01 = "Day4/bigdong01.jpg"
    image bigdong02 = "Day4/bigdong02.jpg"
    image bigdongall = "Day4/bigdongall.jpg"
    image bigdongall02 = "Day4/bigdongall02.jpg"
    image bigdongall03 = "Day4/bigdongall03.jpg"
    image bigdongall04 = "Day4/bigdongall04.jpg"
    image bigdongbus = "Day4/bigdongbus.jpg"
    image bigdongbus02 = "Day4/bigdongbus02.jpg"
    image bigdongdouble01 = "Day4/bigdongdouble01.jpg"
    image bigdongend = "Day4/bigdongend.jpg"
    image bigdongfrieda01 = "Day4/bigdongfrieda01.jpg"
    image bigdongnobody = "Day4/bigdongnobody.jpg"
    image bigdongteagan01 = "Day4/bigdongteagan01.jpg"
    image bigdongteagan02 = "Day4/bigdongteagan02.jpg"
    image bigdongteagan03 = "Day4/bigdongteagan03.jpg"
    image bigdongteagan04 = "Day4/bigdongteagan04.jpg"
    image bigdongteagan05 = "Day4/bigdongteagan05.jpg"
    image bigdongviviane01 = "Day4/bigdongviviane01.jpg"
    image bigdongviviane02 = "Day4/bigdongviviane02.jpg"
    image bigdongviviane03 = "Day4/bigdongviviane03.jpg"
    image bigdongviviane04 = "Day4/bigdongviviane04.jpg"
    image bigdongviviane05 = "Day4/bigdongviviane05.jpg"
    image bigdongviviane06 = "Day4/bigdongviviane06.jpg"

    image bothcum01 = "Day4/bothcum01.jpg"
    image bothcum02 = "Day4/bothcum02.jpg"
    image bothcum03 = "Day4/bothcum03.jpg"
    image bothplay01 = "Day4/bothplay01.jpg"
    image bothplay02 = "Day4/bothplay02.jpg"
    image bothplay03 = "Day4/bothplay03.jpg"
    image bothplay03b = "Day4/bothplay03b.jpg"
    image bothworship01 = "Day4/bothworship01.jpg"
    image bothworship02 = "Day4/bothworship02.jpg"


    image britbeach01 = "Day4/britbeach01.jpg"
    image britbeach02 = "Day4/britbeach02.jpg"
    image britbeach03 = "Day4/britbeach03.jpg"
    image britbeach04 = "Day4/britbeach04.jpg"
    image britbeach05 = "Day4/britbeach05.jpg"
    image britbeach06 = "Day4/britbeach06.jpg"
    image britbeach07 = "Day4/britbeach07.jpg"
    image britbeach08 = "Day4/britbeach08.jpg"

    image breakfastday04 = "Day4/breakfastday04.jpg"
    image breakfastday04b = "Day4/breakfastday04b.jpg"
    image mommorning01 = "Day4/mommorning01.jpg"
    image mommorning02 = "Day4/mommorning02.jpg"
    image mommorning03 = "Day4/mommorning03.jpg"
    image mommorning04 = "Day4/mommorning04.jpg"
   
    image pole01 = "Day4/pole01.jpg"
    image pole02 = "Day4/pole02.jpg"
    image pole03 = "Day4/pole03.jpg"
    image pole04 = "Day4/pole04.jpg"
    image pole04b = "Day4/pole04b.jpg"
    image pole05 = "Day4/pole05.jpg"
    image pole06 = "Day4/pole06.jpg"
    image pole06b = "Day4/pole06b.jpg"
    image pole07 = "Day4/pole07.jpg"
    image pole08 = "Day4/pole08.jpg"
    image pole09 = "Day4/pole09.jpg"
    image pole10 = "Day4/pole10.jpg"
    image pole11 = "Day4/pole11.jpg"
    image pole12 = "Day4/pole12.jpg"
    image pole13 = "Day4/pole13.jpg"
    image pole14 = "Day4/pole14.jpg"
    image polebuild01 = "Day4/polebuild01.jpg"
    image polebuild02 = "Day4/polebuild02.jpg"
    image storephone = "Day4/storephone.jpg"

    image clinic01 = "Day4/clinic01.jpg"
    image clinic02 = "Day4/clinic02.jpg"
    image clinic03 = "Day4/clinic03.jpg"
    image clinic04 = "Day4/clinic04.jpg"
    image clinic05 = "Day4/clinic05.jpg"
    image clinic06 = "Day4/clinic06.jpg"
    image clinic07 = "Day4/clinic07.jpg"
    image clinic08 = "Day4/clinic08.jpg"
    image clinic09 = "Day4/clinic09.jpg"
    image clinic10 = "Day4/clinic10.jpg"
    image clinic11 = "Day4/clinic11.jpg"
    image clinic12 = "Day4/clinic12.jpg"
    image clinic13 = "Day4/clinic13.jpg"
    image clinic14 = "Day4/clinic14.jpg"
    image clinic15 = "Day4/clinic15.jpg"

    image copblow01 = "Day4/copblow01.jpg"
    image copblow02 = "Day4/copblow02.jpg"
    image copblow03 = "Day4/copblow03.jpg"
    image copfuck01 = "Day4/copfuck01.jpg"
    image copfuck02 = "Day4/copfuck02.jpg"
    image copfuckcum01 = "Day4/copfuckcum01.jpg"
    image copfuckcum02 = "Day4/copfuckcum02.jpg"

    image dorisbell01 = "Day4/dorisbell01.jpg"
    image dorisbell02 = "Day4/dorisbell02.jpg"
    image dorisbell03 = "Day4/dorisbell03.jpg"
    image dorisbell04 = "Day4/dorisbell04.jpg"
    image dorisbell05 = "Day4/dorisbell05.jpg"
    image dorisbell06 = "Day4/dorisbell06.jpg"
    image dorisbell07 = "Day4/dorisbell07.jpg"
    image dorisbell08 = "Day4/dorisbell08.jpg"
    image dorisbell09 = "Day4/dorisbell09.jpg"
    image dorisbell10 = "Day4/dorisbell10.jpg"

    image emporium01 = "Day4/emporium01.jpg"
    image emporium02 = "Day4/emporium02.jpg"
    image emporium03 = "Day4/emporium03.jpg"

    image cabin01 = "Day4/cabin01.jpg"
    image cabin02 = "Day4/cabin02.jpg"
    image cabin03 = "Day4/cabin03.jpg"
    image cabin04 = "Day4/cabin04.jpg"
    image maddybeach01 = "Day4/maddybeach01.jpg"
    image maddybeach02 = "Day4/maddybeach02.jpg"
    image maddybeach03 = "Day4/maddybeach03.jpg"
    image maddybeach04 = "Day4/maddybeach04.jpg"
    image maddyfoot01 = "Day4/maddyfoot01.jpg"
    image maddyfoot02 = "Day4/maddyfoot02.jpg"
    image maddyfoot03 = "Day4/maddyfoot03.jpg"
    image maddyfuck01 = "Day4/maddyfuck01.jpg"
    image maddyfuck02 = "Day4/maddyfuck02.jpg"
    image maddyfuck03 = "Day4/maddyfuck03.jpg"
    image maddyfuck04 = "Day4/maddyfuck04.jpg"
    image maddyfuck05 = "Day4/maddyfuck05.jpg"
    image maddyfuck05b = "Day4/maddyfuck05b.jpg"
    image maddyfuck03b = "Day4/maddyfuck03b.jpg"
    image maddyfuck03c = "Day4/maddyfuck03c.jpg"
    image maddyfoot01 = "Day4/maddyfoot01.jpg"
    image maddyfoot02 = "Day4/maddyfoot02.jpg"
    image maddyfoot03 = "Day4/maddyfoot03.jpg"

    image mariafuck01 = "Day4/mariafuck01.jpg"
    image mariafuck02 = "Day4/mariafuck02.jpg"
    image mariafuck03 = "Day4/mariafuck03.jpg"
    image mariafuck04 = "Day4/mariafuck04.jpg"
    image tanning01 = "Day4/tanning01.jpg"
    image tanning02 = "Day4/tanning02.jpg"
    image tanning03 = "Day4/tanning03.jpg"
    image tanning04 = "Day4/tanning04.jpg"

    image tanyabed01 = "Day4/tanyabed01.jpg"
    image tanyabed02 = "Day4/tanyabed02.jpg"
    image tanyabed03 = "Day4/tanyabed03.jpg"
    image tanyabed04 = "Day4/tanyabed04.jpg"
    image tanyabed05 = "Day4/tanyabed05.jpg"
    image tanyabed06 = "Day4/tanyabed06.jpg"
    image tanyabed07 = "Day4/tanyabed07.jpg"
    image tanyabed08 = "Day4/tanyabed08.jpg"
    image tanyabed08b = "Day4/tanyabed08b.jpg"
    image tanyabed09 = "Day4/tanyabed09.jpg"
    image tanyabed09b = "Day4/tanyabed09b.jpg"
    image tanyabed10 = "Day4/tanyabed10.jpg"
    image tanyabed11 = "Day4/tanyabed11.jpg"
    image tanyabed11b = "Day4/tanyabed11b.jpg"
    image tanyabed11c = "Day4/tanyabed11c.jpg"
    image tanyabed12 = "Day4/tanyabed12.jpg"
    image tanyabed13 = "Day4/tanyabed13.jpg"
    image tanyabed14 = "Day4/tanyabed14.jpg"
    image tanyabed14b = "Day4/tanyabed14b.jpg"
    image tanyabed15 = "Day4/tanyabed15.jpg"

    image tshirtchantelle01 = "Day4/tshirtchantelle01.png"
    image tshirtchantelle02 = "Day4/tshirtchantelle02.png"
    image tshirtchantelle03 = "Day4/tshirtchantelle03.png"
    image tshirtchantelle04 = "Day4/tshirtchantelle04.png"
    image tshirtdoris01 = "Day4/tshirtdoris01.png"
    image tshirtdoris02 = "Day4/tshirtdoris02.png"
    image tshirtdoris03 = "Day4/tshirtdoris03.png"
    image tshirtdoris04 = "Day4/tshirtdoris04.png"
    image tshirthalle01 = "Day4/tshirthalle01.png"
    image tshirthalle02 = "Day4/tshirthalle02.png"
    image tshirthalle04 = "Day4/tshirthalle03.png"
    image tshirthalle01 = "Day4/tshirthalle04.png"
    image tshirtsandy01 = "Day4/tshirtsandy01.png"
    image tshirtsandy02 = "Day4/tshirtsandy02.png"
    image tshirtsandy03 = "Day4/tshirtsandy03.png"
    image tshirtsandy04 = "Day4/tshirtsandy04.png"


    image buskate01 = "Day4/buskate01.jpg"
    image buskate02 = "Day4/buskate02.jpg"
    image busquentin01 = "Day4/busquentin01.jpg"
    image busquentin02 = "Day4/busquentin02.jpg"
    image buslaura01 = "Day4/buslaura01.jpg"
    image buslaura02 = "Day4/buslaura02.jpg"
    image mariabus = "Day4/mariabus.jpg"
    image security04 = "Day4/security04.png"

    image randyshop01 = "Day4/randyshop01.jpg"
    image randyshop02 = "Day4/randyshop02.jpg"
    image randyshop03 = "Day4/randyshop03.jpg"
    image randyshop04 = "Day4/randyshop04.jpg"
    image randyshop05 = "Day4/randyshop05.jpg"
    image randyshop06 = "Day4/randyshop06.jpg"
    image randyshop07 = "Day4/randyshop07.jpg"
    image sandycpr = "Day4/sandycpr.jpg"

# Day6 images

    image pamelastand01 = "Day6/pamelastand01.jpg"
    image pamelastand02 = "Day6/pamelastand02.jpg"
    image pamelasea01 = "Day6/pamelasea01.jpg"
    image pamelasea02 = "Day6/pamelasea02.jpg"
    image pamelasea03 = "Day6/pamelasea03.jpg"
    image pamelasea04 = "Day6/pamelasea04.jpg"
    image pamelasea05 = "Day6/pamelasea05.jpg"
    image pamelasea06 = "Day6/pamelasea06.jpg"
    image pamelasea07 = "Day6/pamelasea07.jpg"
    image pamelasea08 = "Day6/pamelasea08.jpg"
    image pamelaprefuck01 = "Day6/pamelaprefuck01.jpg"
    image pamelaprefuck01b = "Day6/pamelaprefuck01b.jpg"
    image pamelaprefuck02 = "Day6/pamelaprefuck03.jpg"
    image pamelaprefuck03 = "Day6/pamelaprefuck03.jpg"
    image pameladoggy01 = "Day6/pameladoggy01.jpg"
    image pameladoggy02 = "Day6/pameladoggy02.jpg"
    image pameladoggy03 = "Day6/pameladoggy03.jpg"
    image pameladoggy04 = "Day6/pameladoggy04.jpg"
    image pamelablow01 = "Day6/pamelablow01.jpg"
    image pamelablow02 = "Day6/pamelablow02.jpg"
    image pamelablow03 = "Day6/pamelablow03.jpg"
    image pamelablow04 = "Day6/pamelablow04.jpg"
    image pamelacum01 = "Day6/pamelacum01.jpg"
    image pamelacum02 = "Day6/pamelacum02.jpg"
    image pamelacum03 = "Day6/pamelacum03.jpg"
    image pamanal01 = "Day6/pamanal01.jpg"
    image pamanal02 = "Day6/pamanal02.jpg"
    image pamanal03 = "Day6/pamanal03.jpg"
    image chantellelick01 = "Day6/chantellelick01.jpg"
    image chantellelick02 = "Day6/chantellelick02.jpg"
    image chantellelick03 = "Day6/chantellelick03.jpg"
    image chantelleball01 = "Day6/chantelleball01.jpg"
    image chantelleball02 = "Day6/chantelleball02.jpg"
    image chantelleball03 = "Day6/chantelleball03.jpg"
    image chantellefloor01 = "Day6/chantellefloor01.jpg"
    image chantellefloor02 = "Day6/chantellefloor02.jpg"
    image chantellepreblow = "Day6/chantellepreblow.jpg"
    image chantelleblow01 = "Day6/chantelleblow01.jpg"
    image chantelleblow02 = "Day6/chantelleblow02.jpg"
    image chantelleblow03 = "Day6/chantelleblow03.jpg"
    image chantellecum01 = "Day6/chantellecum01.jpg"
    image chantellecum02 = "Day6/chantellecum02.jpg"
    image chantellecum03 = "Day6/chantellecum03.jpg"
    image britanal01 = "Day6/britanal01.jpg"
    image britanal02 = "Day6/britanal02.jpg"
    image britanal03 = "Day6/britanal03.jpg"
    image britcum01 = "Day6/britcum01.jpg"
    image britcum02 = "Day6/britcum02.jpg"
    image britcum03 = "Day6/britcum03.jpg"
    image britdoggy01 = "Day6/britdoggy01.jpg"
    image britdoggy02 = "Day6/britdoggy02.jpg"
    image britdoggy03 = "Day6/britdoggy03.jpg"
    image britfloor01 = "Day6/britfloor01.jpg"
    image britfloor02 = "Day6/britfloor02.jpg"
    image britfuckup01 = "Day6/britfuckup01.jpg"
    image britfuckup02 = "Day6/britfuckup02.jpg"
    image britfuckup05 = "Day6/britfuckup05.jpg"
    image britfuckup04 = "Day6/britfuckup04.jpg"
    image britprefuck01 = "Day6/britprefuck01.jpg"
    image britprefuck02 = "Day6/britprefuck02.jpg"
    image britprefuck03 = "Day6/britprefuck03.jpg"
    image britprefuck04 = "Day6/britprefuck04.jpg"
    image both01 = "Day6/both01.jpg"
    image both02 = "Day6/both02.jpg"
    image both03 = "Day6/both03.jpg"
    image both04 = "Day6/both04.jpg"
    image bothchantelle01 = "Day6/bothchantelle01.jpg"
    image bothchantelle02 = "Day6/bothchantelle02.jpg"
    image bothhouse01 = "Day6/bothhouse01.jpg"
    image bothhouse02 = "Day6/bothhouse02.jpg"
    image bothhouse03 = "Day6/bothhouse03.jpg"
    image bothhouse04 = "Day6/bothhouse04.jpg"
    image bothhouse05 = "Day6/bothhouse05.jpg"
    image bothhouse06 = "Day6/bothhouse06.jpg"
    image bothoral01 = "Day6/bothoral01.jpg"
    image bothoral02 = "Day6/bothoral02.jpg"
    image bothoral03 = "Day6/bothoral03.jpg"
    image bothoral04 = "Day6/bothoral04.jpg"
    image bothoral05 = "Day6/bothoral05.jpg"
    image bothoral06 = "Day6/bothoral06.jpg"
    image bothsiscum01 = "Day6/bothsiscum01.jpg"
    image bothsiscum02 = "Day6/bothsiscum02.jpg"
    image bothsiscum03 = "Day6/bothsiscum03.jpg"
    image bothsiscum04 = "Day6/bothsiscum04.jpg"
    image bothsisfuck01 = "Day6/bothsisfuck01.jpg"
    image bothsisfuck02 = "Day6/bothsisfuck02.jpg"
    image bothsisfuck03 = "Day6/bothsisfuck03.jpg"
    image bothsisfuck04 = "Day6/bothsisfuck04.jpg"
    image bothtitfuck01 = "Day6/bothtitfuck01.jpg"
    image bothtitfuck02 = "Day6/bothtitfuck02.jpg"
    image bothtitfuck03 = "Day6/bothtitfuck03.jpg"
    image debbytopless01 = "Day6/debbytopless01.jpg"
    image debbytopless02 = "Day6/debbytopless02.jpg"
    image debbytopless03 = "Day6/debbytopless03.jpg"
    image debbytopless04 = "Day6/debbytopless04.jpg"
    image debbytopless05 = "Day6/debbytopless05.jpg"
    image debbytopless06 = "Day6/debbytopless06.jpg"
    image debbytopless07 = "Day6/debbytopless07.jpg"
    image debbytopless08 = "Day6/debbytopless08.jpg"
    image debbytopless09 = "Day6/debbytopless09.jpg"
    image swimlesson01 = "Day6/swimlesson01.jpg"
    image swimlesson02 = "Day6/swimlesson02.jpg"
    image swimlesson03 = "Day6/swimlesson03.jpg"
    image swimlesson04 = "Day6/swimlesson04.jpg"
    image swimlesson05 = "Day6/swimlesson05.jpg"
    image swimlesson06 = "Day6/swimlesson06.jpg"
    image swimlesson07 = "Day6/swimlesson07.jpg"
    image swimlesson08 = "Day6/swimlesson08.jpg"
    image swimlesson08b = "Day6/swimlesson08b.jpg"
    image swimlesson09 = "Day6/swimlesson09.jpg"
    image swimlesson11 = "Day6/swimlesson11.jpg"
    image pamelaprefuck02 = "Day6/pamelaprefuck02.jpg"
    image pamelaprefuck01 = "Day6/pamelaprefuck01.jpg"
    image pamelaprefuck03 = "Day6/pamelaprefuck03.jpg"
    image pamelaprefuck01b = "Day6/pamelaprefuck01b.jpg"
    image pamelafuckmovie = "Day6/pamelafuckmovie.jpg"
    image britfuckpremovie = "Day6/britfuckpremovie.jpg"
    image chantellefuckmovie = "Day6/chantellefuckmovie.jpg"
    image chantellegymday06 = "Day6/chantellegymday06.jpg"
    image chantellegymday06b = "Day6/chantellegymday06b.jpg"
    image chantellehypno = "Day6/chantellehypno.jpg"
    image chantellechoice01 = "Day6/chantellechoice01.jpg"
    image chantellecumfill = "Day6/chantellecumfill.jpg"
    image chantellepheromone = "Day6/chantellepheromone.jpg"
    image chantelleprefuck01 = "Day6/chantelleprefuck01.jpg"
    image chantelleprefuck02 = "Day6/chantelleprefuck02.jpg"
    image chantelleprep01 = "Day6/chantelleprep01.jpg"
    image chantelleprep01a = "Day6/chantelleprep01a.jpg"
    image chantelleprep02 = "Day6/chantelleprep02.jpg"
    image chantelleprep03 = "Day6/chantelleprep03.jpg"
    image chantelleprep04a = "Day6/chantelleprep04a.jpg"
    image chantelleprep04b = "Day6/chantelleprep04b.jpg"
    image chantelleprep05 = "Day6/chantelleprep05.jpg"
    image classhappyday06 = "Day6/classhappyday06.jpg"
    image classhappyday06b = "Day6/classhappyday06b.jpg"
    image classjose01day06 = "Day6/classjose01day06.jpg"
    image classjose02day06 = "Day6/classjose02day06.jpg"
    image dancebackground = "Day6/dancebackground.jpg"
    image debbyhousewall = "Day6/debbyhousewall.jpg"
    image principalcum02b = "Day6/principalcum02b.jpg"
    image randybeach01empty = "Day6/randybeach01empty.jpg"
    image randybeach02empty = "Day6/randybeach02empty.jpg"
    image randybeach03empty = "Day6/randybeach03empty.jpg"
    image randyred01 = "Day6/randyred01.jpg"
    image randyred02 = "Day6/randyred02.jpg"
    image randyred03 = "Day6/randyred03.jpg"
    image randyred04 = "Day6/randyred04.jpg"
    image randyred05 = "Day6/randyred05.jpg"
    image randyred05b = "Day6/randyred05b.jpg"
    image randyred06 = "Day6/randyred06.jpg"
    
# icon images

    image failsmall = "Icons/failsmall.png"
    image winsmall = "Icons/winsmall.png"
    image lust01 = "Icons/lustplus01.png"
    image lust02 = "Icons/lustplus02.png"
    image lust03 = "Icons/lustplus03.png"
    image lust05 = "Icons/lustplus05.png"
    image epiclust = "Icons/epiclust.png"
    image doubledelight = "Icons/doubledelight.png"
    image lustminus01 = "Icons/lustminus01.png"
    image lustminus02 = "Icons/lustminus02.png"
    image strength01 = "Icons/strengthplus01.png"
    image strengthminus = "Icons/strengthminus01.png"
    image strengthminus01 = "Icons/strengthminus01.png"
    image stamina01 = "Icons/staminaplus01.png"
    image stamina02 = "Icons/staminaplus02.png"
    image staminaminus01 = "Icons/staminaminus01.png"
    image staminaminus02 = "Icons/staminaminus02.png"
    image addedlocation = "Icons/addedlocation.png"
    image statsbackground = "Icons/statsbackground.png"
    image challengerlustminus01 = "Icons/challengerlustminus01.png"
    image challengerlustminus02 = "Icons/challengerlustminus02.png"
    image challengerlustminus03 = "Icons/challengerlustminus03.png"
    image challengerlustplus01 = "Icons/challengerlustplus01.png"
    image challengerlustplus02 = "Icons/challengerlustplus02.png"
    image challengerlustplus03 = "Icons/challengerlustplus03.png"
    image challengerlustplus05= "Icons/challengerlustplus05.png"
    image clock = "Icons/timer.png"
    image credits = "Icons/credits.png"
    image faster = "Icons/faster.png"
    image next = "Icons/next.png"
    image cum = "Icons/cum.png"
    image day01 = "Icons/day01.png"
    image day02 = "Icons/day02.png"
    image day03 = "Icons/day03.png"
    image day04 = "Icons/day04.png"
    image day05 = "Icons/day05.png"
    image inventory = "Icons/inventorybackground.png"
    image exitbrown = "Icons/exitbrown.png"
    image topbrown = "Icons/topbrown.png"
    image topred = "Icons/topred.png"
    image exitred = "Icons/exitred.png"
    image toporange = "Icons/toporange.png"
    image exitorange = "Icons/exitorange.png"
    image topyellow = "Icons/topyellow.png"
    image exityellow = "Icons/exityellow.png"
    image toppurple = "Icons/toppurple.png"
    image exitpurple = "Icons/exitpurple.png"
    image exitgrey = "Icons/exitgrey.png"
    image topgrey = "Icons/topgrey.png"
    image exitblue = "Icons/exitblue.png"
    image topblue = "Icons/topblue.png"
    image exitgreen = "Icons/exitgreen.png"
    image topgreen = "Icons/topgreen.png"
    image exitcharactersheets = "Icons/exitcharactersheets.png"
    image achievement01 = "Icons/achievement01.png"
    image achievement02 = "Icons/achievement02.png"
    image achievement03 = "Icons/achievement03.png"
    image achievement04 = "Icons/achievement04.png"
    image achievement05 = "Icons/achievement05.png"
    image achievement06 = "Icons/achievement06.png"
    image achievement07 = "Icons/achievement07.png"
    image achievement08 = "Icons/achievement08.png"
    image achievement09 = "Icons/achievement09.png"
    image achievement10 = "Icons/achievement10.png"
    image achievement11 = "Icons/achievement11.png"
    image achievement12 = "Icons/achievement12.png"
    image achievement13 = "Icons/achievement13.png"
    image achievement14 = "Icons/achievement14.png"
    image achievement15 = "Icons/achievement15.png"
    image achievement16 = "Icons/achievement16.png"
    image achievement17 = "Icons/achievement17.png"
    image achievement18 = "Icons/achievement18.png"
    image achievement19 = "Icons/achievement19.png"
    image achievement20 = "Icons/achievement20.png"
    image achievement21 = "Icons/achievement21.png"
    image achievement22 = "Icons/achievement22.png"
    image achievement23 = "Icons/achievement23.png"
    image achievement24 = "Icons/achievement24.png"
    image sophiabutton = "Icons/sophiabutton.png"
    image vivianebutton = "Icons/vivianebutton.png"
    image friedabutton = "Icons/friedabutton.png"
    image leavebutton = "Icons/leavebutton.png"

# map images
    image islandmap = "Map/islandmap.jpg"
    image randybeachmap = "Map/randybeachmap.png"
    image schoolmap = "Map/schoolmap.png"
    image gymmap = "Map/gymmap.png"
    image aunthousemap = "Map/aunthousemap.png"
    image parlourmap = "Map/parlourmap.png"
    image storemap = "Map/storemap.png"
    image audaciousmap = "Map/audaciousmap.png"
    image tanyamap = "Map/tanyamap.png"
    image teaganmap = "Map/teaganmap.png"
    image cabinmap = "Map/cabinmap.png"
    image waterfallsmap = "Map/waterfallsmap.png"
    image clinicmap = "Map/clinicmap.png"
    image annamap = "Map/annamap.png"
    
# overlaid images

    image randybeachparasol01 = "Day1/randybeachparasol01.png"
    image randybeachparasol02 = "Day1/randybeachparasol02.png"
    image randybeachparasol03 = "Day1/randybeachparasol03.png"
    image randybeacholdwoman01 = "Day1/randybeacholdwoman01.png"
    image randybeacholdwoman02 = "Day1/randybeacholdwoman02.png"
    image ryanrandybeach = "Day1/ryanrandybeach.png"
    
# Phone pics

    image joseanna = "Phone/joseanna.png"
    image josebrittany = "Phone/josebrittany.png"
    image josechantelle = "Phone/josechantelle.png"
    image josechiyo = "Phone/josechiyo.png"
    image josedaniella = "Phone/josedaniella.png"
    image josedebby = "Phone/josedebby.png"
    image josedoris = "Phone/josedoris.png"
    image josefrancine = "Phone/josefrancine.png"
    image josefrieda = "Phone/josefrieda.png"
    image josehalle = "Phone/josehalle.png"
    image josejennifer = "Phone/josejennifer.png"
    image josekate = "Phone/josekate.png"
    image josekatsumi = "Phone/josekatsumi.png"
    image joselaura = "Phone/joselaura.png"
    image josemaddy = "Phone/josemaddy.png"
    image josemaria = "Phone/josemaria.png"
    image josenancy = "Phone/josenancy.png"
    image josenikki = "Phone/josenikki.png"
    image josepamela = "Phone/josepamela.png"
    image josesandy = "Phone/josesandy.png"
    image josesophia = "Phone/josesophia.png"
    image josetanya = "Phone/josetanya.png"
    image joseteagan = "Phone/joseteagan.png"
    image joseviviane = "Phone/joseviviane.png"
    
# Inventory

    image inventorybackground = "Inventory/inventorybackground.png"
    image audaciouspass = "Inventory/audaciouspassb.png"
    image audaciouspassidle = "Inventory/audaciouspassidle.png"
    image audaciouspasshover = "Inventory/audaciouspasshover.png"
    image camera = "Inventory/camerab.png"
    image cameraidle = "Inventory/cameraidle.png"
    image camerahover = "Inventory/camerahover.png"
    image book = "Inventory/bookb.png"
    image bookidle = "Inventory/bookidle.png"
    image bookhover = "Inventory/bookhover.png"
    image beercase = "Inventory/beercaseb.png"
    image beercaseidle = "Inventory/beercaseidle.png"
    image beercasehover = "Inventory/beercasehover.png"
    image dildo = "Inventory/dildob.png"
    image dildoidle = "Inventory/dildoidle.png"
    image dildohover = "Inventory/dildohover.png"
    image flower = "Inventory/flowerb.png"
    image floweridle = "Inventory/floweridle.png"
    image flowerhover = "Inventory/flowerhover.png"
    image knife = "Inventory/knifeb.png"
    image knifeidle = "Inventory/knifeidle.png"
    image knifehover = "Inventory/knifehover.png"
    image goldcoin = "Inventory/goldcoinb.png"
    image goldcoinidle = "Inventory/goldcoinidle.png"
    image goldcoinhover = "Inventory/goldcoinhover.png"
    image megacondoms = "Inventory/megacondomsb.png"
    image megacondomsidle = "Inventory/megacondomsidle.png"
    image megacondomshover = "Inventory/megacondomshover.png"
    image pheromone = "Inventory/pheromoneb.png"
    image pheromoneidle = "Inventory/pheromoneidle.png"
    image pheromonehover = "Inventory/pheromonehover.png"
    image tanktop = "Inventory/tanktopb.png"
    image tanktopidle = "Inventory/tanktopidle.png"
    image tanktophover = "Inventory/tanktophover.png"
    image wd69 = "Inventory/wd69b.png"
    image wd69idle = "Inventory/wd69idle.png"
    image wd69hover = "Inventory/wd69hover.png"
    image whitebull = "Inventory/whitebullb.png"
    image whitebullidle = "Inventory/whitebullidle.png"
    image whitebullhover = "Inventory/whitebullhover.png"
    image pendulum = "Inventory/pendulumb.png"
    image pendulumidle = "Inventory/pendulumidle.png"
    image pendulumhover = "Inventory/pendulumhover.png"
    image wristband = "Inventory/wristbandb.png"
    image wristbandidle = "Inventory/wristbandidle.png"
    image wristbandhover = "Inventory/wristbandhover.png"
    image bluepills = "Inventory/bluepillsb.png"
    image redpills = "Inventory/redpillsb.png"
    image bluepillsx2 = "Inventory/bluepillsx2.png"
    image redpillsx2 = "Inventory/redpillsx2.png"
    image bluepillsx1 = "Inventory/bluepillx1.png"
    image redpillsx1 = "Inventory/redpillx1.png"
    image wristbandhover = "Inventory/wristbandhover.png"
    image pendulum01 = "Inventory/pendulum01.png"
    image pendulum02 = "Inventory/pendulum02.png"
    image pendulum03 = "Inventory/pendulum03.png"
    image pendulum04 = "Inventory/pendulum04.png"
    image pendulum05 = "Inventory/pendulum05.png"
    image pendulumsnapped = "Inventory/pendulumsnapped.png"
    image square = "Inventory/square.png"

# map images

    image notavailable = "Achievements/notavailable.jpg"
    image achievementbackground = "Achievements/achievementbackground.jpg"
    image debbynewbikinipool blurred = im.Blur("Day7/debbynewbikinipool.jpg", 1.2)
    image debbynewbikinipool = "Day7/debbynewbikinipool.jpg"
    image debbysec04 = "Day7/debbysec04.png"
    image debbysec05 = "Day7/debbysec05.png"
    image debbysec06 = "Day7/debbysec06.png"
    image debbysec0cum01 = "Day7/debbyseccum01.png"
