name: Build Ren'Py iOS App

on: push

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Cache repository checkout
        id: cache-checkout
        uses: actions/cache@v3
        with:
          path: |
            .git
            .
          key: checkout-${{ github.sha }}-${{ runner.os }}
          restore-keys: |
            checkout-

      - name: Get latest Ren'Py version
        run: |
          LATEST_VERSION=$(curl -s https://www.renpy.org/dl/update.json | jq -r '.latest')
          echo "LATEST_VERSION=$LATEST_VERSION" >> $GITHUB_ENV

      - name: Set SDK directory
        run: |
          SDK_DIR=renpy/renpy-${{ env.LATEST_VERSION }}-sdk
          echo "SDK_DIR=$SDK_DIR" >> $GITHUB_ENV

      - name: Cache Ren'Py SDK
        id: cache-renpy
        uses: actions/cache@v3
        with:
          path: renpy
          key: renpy-${{ env.LATEST_VERSION }}-${{ runner.os }}
          restore-keys: |
            renpy-

      - name: Download Ren'Py SDK
        if: steps.cache-renpy.outputs.cache-hit != 'true'
        run: |
          curl -o renpy-sdk.zip https://www.renpy.org/dl/${{ env.LATEST_VERSION }}/renpy-${{ env.LATEST_VERSION }}-sdk.zip
          unzip renpy-sdk.zip -d renpy

      - name: Download and install rapt
        if: steps.cache-renpy.outputs.cache-hit != 'true'
        run: |
          curl -o rapt.zip https://www.renpy.org/dl/${{ env.LATEST_VERSION }}/renpy-${{ env.LATEST_VERSION }}-rapt.zip
          unzip rapt.zip -d ${{ env.SDK_DIR }}

      - name: Download and install renios
        if: steps.cache-renpy.outputs.cache-hit != 'true'
        run: |
          curl -o renios.zip https://www.renpy.org/dl/${{ env.LATEST_VERSION }}/renpy-${{ env.LATEST_VERSION }}-renios.zip
          unzip renios.zip -d ${{ env.SDK_DIR }}

      - name: Download and install renpyweb
        if: steps.cache-renpy.outputs.cache-hit != 'true'
        run: |
          curl -o renpyweb.zip https://www.renpy.org/dl/${{ env.LATEST_VERSION }}/renpy-${{ env.LATEST_VERSION }}-web.zip
          unzip renpyweb.zip -d ${{ env.SDK_DIR }}

      - name: Build for iOS
        run: |
          cd ${{ env.SDK_DIR }}
          ./renpy.sh launcher ios_create "$GITHUB_WORKSPACE" "$GITHUB_WORKSPACE/ios"
          ./renpy.sh launcher ios_populate "$GITHUB_WORKSPACE" "$GITHUB_WORKSPACE/ios"
          echo "Contents of $GITHUB_WORKSPACE/ios:"
          ls -la "$GITHUB_WORKSPACE/ios"